// 영어회화 빈출 단어 데이터
// w: 단어, p: 발음, m: 뜻, ex: [[영어 예문, 한글 해석], ...]
const WORDS = [
  { id: 1, w: "grab", p: "[ɡræb] 그랩", m: "잡다; (간단히) 먹다, 마시다", ex: [["Let's grab a coffee sometime.", "언제 커피 한잔하자."], ["Can you grab my bag for me?", "내 가방 좀 집어줄래?"]] },
  { id: 2, w: "hang out", p: "[hæŋ aʊt] 행 아웃", m: "놀다, 시간을 보내다", ex: [["Do you want to hang out this weekend?", "이번 주말에 같이 놀래?"], ["I usually hang out with my friends after work.", "나는 보통 퇴근 후에 친구들이랑 놀아."]] },
  { id: 3, w: "figure out", p: "[ˈfɪɡjər aʊt] 피겨 아웃", m: "알아내다, 이해하다", ex: [["I can't figure out how to use this app.", "이 앱을 어떻게 쓰는지 모르겠어."], ["We'll figure it out together.", "우리 같이 방법을 찾아보자."]] },
  { id: 4, w: "awesome", p: "[ˈɔːsəm] 어썸", m: "굉장한, 멋진", ex: [["That movie was awesome!", "그 영화 진짜 멋졌어!"], ["You did an awesome job.", "너 정말 잘했어."]] },
  { id: 5, w: "actually", p: "[ˈæktʃuəli] 액츄얼리", m: "사실은, 실제로", ex: [["Actually, I've never been there.", "사실 나 거기 가본 적 없어."], ["It's actually easier than it looks.", "그거 사실 보기보다 쉬워."]] },
  { id: 6, w: "appointment", p: "[əˈpɔɪntmənt] 어포인트먼트", m: "(병원·업무 등의) 약속, 예약", ex: [["I have a doctor's appointment at 3.", "나 3시에 병원 예약 있어."], ["Can I make an appointment for tomorrow?", "내일로 예약할 수 있을까요?"]] },
  { id: 7, w: "available", p: "[əˈveɪləbl] 어베일러블", m: "시간이 되는; 이용 가능한", ex: [["Are you available this Friday?", "이번 금요일에 시간 돼?"], ["Is this seat available?", "이 자리 비어 있나요?"]] },
  { id: 8, w: "borrow", p: "[ˈbɑːroʊ] 바로우", m: "빌리다", ex: [["Can I borrow your pen?", "펜 좀 빌려도 될까?"], ["I borrowed this book from the library.", "이 책 도서관에서 빌렸어."]] },
  { id: 9, w: "cancel", p: "[ˈkænsl] 캔슬", m: "취소하다", ex: [["I need to cancel my reservation.", "예약을 취소해야 해요."], ["The meeting was canceled.", "회의가 취소됐어."]] },
  { id: 10, w: "comfortable", p: "[ˈkʌmftəbl] 컴프터블", m: "편안한", ex: [["This chair is so comfortable.", "이 의자 정말 편하다."], ["Make yourself comfortable.", "편하게 있어."]] },
  { id: 11, w: "confused", p: "[kənˈfjuːzd] 컨퓨즈드", m: "혼란스러운, 헷갈리는", ex: [["I'm confused. Can you explain again?", "헷갈려요. 다시 설명해 줄래요?"], ["She looked confused by the question.", "그녀는 질문에 헷갈려하는 것 같았어."]] },
  { id: 12, w: "convenient", p: "[kənˈviːniənt] 컨비니언트", m: "편리한", ex: [["Is 2 o'clock convenient for you?", "2시 괜찮으세요?"], ["The subway is really convenient here.", "여기는 지하철이 정말 편리해."]] },
  { id: 13, w: "crowded", p: "[ˈkraʊdɪd] 크라우디드", m: "붐비는, 혼잡한", ex: [["The bus was so crowded this morning.", "오늘 아침 버스 진짜 붐볐어."], ["Let's avoid crowded places.", "붐비는 곳은 피하자."]] },
  { id: 14, w: "definitely", p: "[ˈdefɪnətli] 데피니틀리", m: "확실히, 분명히", ex: [["I'll definitely be there.", "꼭 갈게."], ["This is definitely the best pizza in town.", "이게 확실히 이 동네 최고 피자야."]] },
  { id: 15, w: "delicious", p: "[dɪˈlɪʃəs] 딜리셔스", m: "맛있는", ex: [["This soup is delicious!", "이 수프 맛있다!"], ["Everything was delicious. Thank you.", "전부 맛있었어요. 감사합니다."]] },
  { id: 16, w: "directions", p: "[dəˈrekʃnz] 디렉션즈", m: "길 안내, 방향", ex: [["Could you give me directions to the station?", "역까지 가는 길 좀 알려주실래요?"], ["I'm bad at following directions.", "난 길 찾는 게 서툴러."]] },
  { id: 17, w: "embarrassed", p: "[ɪmˈbærəst] 임배러스트", m: "창피한, 민망한", ex: [["I was so embarrassed when I fell.", "넘어졌을 때 너무 창피했어."], ["Don't be embarrassed. It happens.", "민망해하지 마. 그럴 수 있어."]] },
  { id: 18, w: "exhausted", p: "[ɪɡˈzɔːstɪd] 이그조스티드", m: "몹시 지친, 기진맥진한", ex: [["I'm exhausted after work.", "퇴근하고 나니 완전 지쳤어."], ["You look exhausted. Get some rest.", "너 지쳐 보여. 좀 쉬어."]] },
  { id: 19, w: "favor", p: "[ˈfeɪvər] 페이버", m: "부탁, 호의", ex: [["Can you do me a favor?", "부탁 하나 들어줄래?"], ["I owe you a favor.", "너한테 신세 졌네."]] },
  { id: 20, w: "grateful", p: "[ˈɡreɪtfl] 그레이트풀", m: "감사하는, 고마워하는", ex: [["I'm so grateful for your help.", "도와줘서 정말 고마워."], ["We're grateful to have you here.", "당신이 여기 있어줘서 감사해요."]] },
  { id: 21, w: "hilarious", p: "[hɪˈleriəs] 힐레리어스", m: "아주 웃긴", ex: [["That joke was hilarious!", "그 농담 진짜 웃겼어!"], ["You should watch this video. It's hilarious.", "이 영상 꼭 봐. 완전 웃겨."]] },
  { id: 22, w: "hurry", p: "[ˈhɜːri] 허리", m: "서두르다; 서두름", ex: [["Hurry up, or we'll be late!", "서둘러, 안 그러면 늦어!"], ["There's no hurry. Take your time.", "급할 거 없어. 천천히 해."]] },
  { id: 23, w: "invite", p: "[ɪnˈvaɪt] 인바이트", m: "초대하다", ex: [["I'd like to invite you to my birthday party.", "내 생일 파티에 초대하고 싶어."], ["Thanks for inviting me!", "초대해 줘서 고마워!"]] },
  { id: 24, w: "jealous", p: "[ˈdʒeləs] 젤러스", m: "질투하는, 부러워하는", ex: [["I'm so jealous of your trip!", "네 여행 진짜 부럽다!"], ["He got jealous when he saw us talking.", "걔는 우리가 얘기하는 걸 보고 질투했어."]] },
  { id: 25, w: "lend", p: "[lend] 렌드", m: "빌려주다", ex: [["Can you lend me some money?", "돈 좀 빌려줄 수 있어?"], ["I lent him my umbrella.", "걔한테 우산 빌려줬어."]] },
  { id: 26, w: "mood", p: "[muːd] 무드", m: "기분; 분위기", ex: [["I'm not in the mood to go out.", "나갈 기분이 아니야."], ["She's in a good mood today.", "걔 오늘 기분 좋아."]] },
  { id: 27, w: "nervous", p: "[ˈnɜːrvəs] 너버스", m: "긴장한, 불안한", ex: [["I'm nervous about the interview.", "면접 때문에 긴장돼."], ["Don't be nervous. You'll do great.", "긴장하지 마. 잘할 거야."]] },
  { id: 28, w: "order", p: "[ˈɔːrdər] 오더", m: "주문하다; 주문", ex: [["Are you ready to order?", "주문하시겠어요?"], ["I ordered it online yesterday.", "어제 온라인으로 주문했어."]] },
  { id: 29, w: "owe", p: "[oʊ] 오우", m: "빚지다, 신세 지다", ex: [["How much do I owe you?", "내가 얼마 줘야 하지?"], ["I owe you one!", "신세 한 번 졌네! (고마워!)"]] },
  { id: 30, w: "perfect", p: "[ˈpɜːrfɪkt] 퍼펙트", m: "완벽한; 딱 좋은", ex: [["That time works perfect for me.", "그 시간 나한테 딱 좋아."], ["The weather is perfect today.", "오늘 날씨 완벽하다."]] },
  { id: 31, w: "pick up", p: "[pɪk ʌp] 픽 업", m: "데리러 가다; 찾아오다, 사다", ex: [["I'll pick you up at 7.", "7시에 데리러 갈게."], ["Can you pick up some milk on your way home?", "집에 오는 길에 우유 좀 사다 줄래?"]] },
  { id: 32, w: "plan", p: "[plæn] 플랜", m: "계획; 계획하다", ex: [["Do you have any plans for the weekend?", "주말에 무슨 계획 있어?"], ["We're planning a trip to Jeju.", "우리 제주도 여행 계획 중이야."]] },
  { id: 33, w: "promise", p: "[ˈprɑːmɪs] 프라미스", m: "약속하다; 약속", ex: [["I promise I won't be late.", "늦지 않겠다고 약속할게."], ["You have to keep your promise.", "약속은 지켜야지."]] },
  { id: 34, w: "recommend", p: "[ˌrekəˈmend] 레커멘드", m: "추천하다", ex: [["What do you recommend here?", "여기 뭐가 맛있어요? (추천 메뉴가 뭐예요?)"], ["I highly recommend this book.", "이 책 강력 추천해."]] },
  { id: 35, w: "refund", p: "[ˈriːfʌnd] 리펀드", m: "환불; 환불하다", ex: [["Can I get a refund for this?", "이거 환불 받을 수 있을까요?"], ["They gave me a full refund.", "전액 환불해 줬어."]] },
  { id: 36, w: "regret", p: "[rɪˈɡret] 리그렛", m: "후회하다; 후회", ex: [["I regret not studying English earlier.", "영어 공부를 더 일찍 안 한 게 후회돼."], ["You won't regret it.", "후회하지 않을 거야."]] },
  { id: 37, w: "relax", p: "[rɪˈlæks] 릴랙스", m: "쉬다, 긴장을 풀다", ex: [["I just want to relax at home today.", "오늘은 그냥 집에서 쉬고 싶어."], ["Relax! Everything will be fine.", "긴장 풀어! 다 잘될 거야."]] },
  { id: 38, w: "reservation", p: "[ˌrezərˈveɪʃn] 레저베이션", m: "예약", ex: [["I'd like to make a reservation for two.", "두 명 예약하고 싶은데요."], ["Do you have a reservation?", "예약하셨나요?"]] },
  { id: 39, w: "schedule", p: "[ˈskedʒuːl] 스케줄", m: "일정; 일정을 잡다", ex: [["My schedule is full this week.", "이번 주는 일정이 꽉 찼어."], ["Let's schedule a meeting for Monday.", "월요일로 회의 일정 잡자."]] },
  { id: 40, w: "starving", p: "[ˈstɑːrvɪŋ] 스타빙", m: "몹시 배고픈", ex: [["I'm starving! Let's eat.", "배고파 죽겠어! 밥 먹자."], ["You must be starving after the long trip.", "긴 여행 후라 엄청 배고프겠다."]] },
  { id: 41, w: "stuck", p: "[stʌk] 스턱", m: "갇힌, 막힌, 꼼짝 못 하는", ex: [["I'm stuck in traffic.", "차가 막혀서 꼼짝 못 하고 있어."], ["I'm stuck on this problem.", "이 문제에서 막혔어."]] },
  { id: 42, w: "suggest", p: "[səˈdʒest] 서제스트", m: "제안하다", ex: [["What do you suggest we do?", "우리가 뭘 하면 좋을까? (제안해 줘)"], ["I suggest taking the subway.", "지하철 타는 걸 추천해."]] },
  { id: 43, w: "supposed to", p: "[səˈpoʊzd tu] 서포즈드 투", m: "~하기로 되어 있다", ex: [["You're supposed to be here by 9.", "너 9시까지 오기로 되어 있잖아."], ["What am I supposed to do?", "내가 어떻게 해야 하는 거야?"]] },
  { id: 44, w: "treat", p: "[triːt] 트리트", m: "한턱내다; 대접, 특별한 선물", ex: [["It's my treat today.", "오늘은 내가 살게."], ["Let me treat you to dinner.", "저녁 한턱낼게."]] },
  { id: 45, w: "terrible", p: "[ˈterəbl] 테러블", m: "끔찍한, 형편없는", ex: [["The traffic was terrible today.", "오늘 차 진짜 끔찍하게 막혔어."], ["I feel terrible about what happened.", "그 일은 정말 미안하게 생각해."]] },
  { id: 46, w: "though", p: "[ðoʊ] 도우", m: "~이긴 하지만 (문장 끝에서)", ex: [["It's expensive. It's really good, though.", "비싸긴 해. 그래도 진짜 좋아."], ["Thanks, though.", "그래도 고마워."]] },
  { id: 47, w: "upset", p: "[ʌpˈset] 업셋", m: "속상한, 화가 난", ex: [["Why are you so upset?", "왜 그렇게 속상해해?"], ["She got upset when she heard the news.", "그녀는 그 소식을 듣고 속상해했어."]] },
  { id: 48, w: "used to", p: "[juːst tu] 유스트 투", m: "예전에 ~하곤 했다", ex: [["I used to live in Busan.", "나 예전에 부산 살았어."], ["We used to hang out a lot.", "우리 예전엔 자주 놀았잖아."]] },
  { id: 49, w: "weird", p: "[wɪrd] 위어드", m: "이상한, 기묘한", ex: [["That's so weird.", "그거 진짜 이상하다."], ["I had a weird dream last night.", "어젯밤에 이상한 꿈 꿨어."]] },
  { id: 50, w: "worth", p: "[wɜːrθ] 워스", m: "~할 가치가 있는", ex: [["It's worth a try.", "시도해 볼 만해."], ["The movie is totally worth watching.", "그 영화 진짜 볼 가치 있어."]] },
  { id: 51, w: "excuse", p: "[ɪkˈskjuːs] 익스큐스", m: "변명; 양해를 구하다", ex: [["Excuse me, is anyone sitting here?", "실례합니다, 여기 자리 있나요?"], ["Stop making excuses.", "변명 좀 그만해."]] },
  { id: 52, w: "mind", p: "[maɪnd] 마인드", m: "꺼리다, 신경 쓰다", ex: [["Do you mind if I open the window?", "창문 좀 열어도 될까요?"], ["Never mind. It's not important.", "신경 쓰지 마. 별거 아니야."]] },
  { id: 53, w: "miss", p: "[mɪs] 미스", m: "그리워하다; 놓치다", ex: [["I miss you so much.", "네가 너무 보고 싶어."], ["Hurry, or you'll miss the train!", "서둘러, 안 그러면 기차 놓쳐!"]] },
  { id: 54, w: "bother", p: "[ˈbɑːðər] 바더", m: "귀찮게 하다, 신경 쓰이게 하다", ex: [["Sorry to bother you, but can I ask something?", "귀찮게 해서 미안한데, 뭐 좀 물어봐도 돼?"], ["Don't bother. I'll do it myself.", "신경 쓰지 마. 내가 할게."]] },
  { id: 55, w: "celebrate", p: "[ˈselɪbreɪt] 셀러브레이트", m: "축하하다, 기념하다", ex: [["Let's celebrate your promotion!", "네 승진 축하하자!"], ["How do you celebrate your birthday?", "생일은 어떻게 보내?"]] },
  { id: 56, w: "complain", p: "[kəmˈpleɪn] 컴플레인", m: "불평하다, 항의하다", ex: [["He always complains about work.", "걔는 맨날 일에 대해 불평해."], ["I'd like to complain about the noise.", "소음에 대해 항의하고 싶은데요."]] },
  { id: 57, w: "expect", p: "[ɪkˈspekt] 익스펙트", m: "기대하다, 예상하다", ex: [["I didn't expect to see you here!", "여기서 널 볼 줄 몰랐어!"], ["What did you expect?", "뭘 기대한 거야?"]] },
  { id: 58, w: "literally", p: "[ˈlɪtərəli] 리터럴리", m: "말 그대로, 진짜로", ex: [["I literally just got home.", "나 진짜 방금 집에 왔어."], ["It was literally the best day ever.", "말 그대로 최고의 하루였어."]] },
  { id: 59, w: "on my way", p: "[ɑːn maɪ weɪ] 온 마이 웨이", m: "가는 중인", ex: [["I'm on my way. Be there in 10.", "가는 중이야. 10분 안에 도착해."], ["I'll grab some snacks on my way.", "가는 길에 간식 좀 사 갈게."]] },
  { id: 60, w: "deal", p: "[diːl] 딜", m: "거래, 약속; 좋은 조건", ex: [["It's a deal!", "그렇게 하기로 한 거다! (약속!)"], ["This phone was a really good deal.", "이 폰 진짜 싸게 잘 샀어."]] },
  { id: 61, w: "stop by", p: "[stɑːp baɪ] 스탑 바이", m: "잠깐 들르다", ex: [["Can I stop by your place tonight?", "오늘 밤에 너희 집에 잠깐 들러도 돼?"], ["I stopped by the store on my way home.", "집에 오는 길에 가게에 잠깐 들렀어."]] },
  { id: 62, w: "run into", p: "[rʌn ˈɪntu] 런 인투", m: "우연히 만나다, 마주치다", ex: [["I ran into an old friend yesterday.", "어제 옛 친구를 우연히 만났어."], ["You'll never guess who I ran into!", "내가 누구 마주쳤는지 상상도 못 할걸!"]] },
  { id: 63, w: "look forward to", p: "[lʊk ˈfɔːrwərd tu] 룩 포워드 투", m: "~을 기대하다, 고대하다", ex: [["I'm looking forward to the weekend.", "주말이 너무 기다려져."], ["We look forward to seeing you soon.", "곧 뵙기를 기대할게요."]] },
  { id: 64, w: "get along", p: "[ɡet əˈlɔːŋ] 겟 얼롱", m: "사이좋게 지내다", ex: [["Do you get along with your coworkers?", "직장 동료들이랑 잘 지내?"], ["We get along really well.", "우린 정말 잘 지내."]] },
  { id: 65, w: "work out", p: "[wɜːrk aʊt] 워크 아웃", m: "운동하다; (일이) 잘 풀리다", ex: [["I work out three times a week.", "나 일주일에 세 번 운동해."], ["Don't worry. It'll all work out.", "걱정 마. 다 잘 풀릴 거야."]] },
  { id: 66, w: "show up", p: "[ʃoʊ ʌp] 쇼 업", m: "나타나다, 오다", ex: [["He didn't show up to the meeting.", "걔 회의에 안 나타났어."], ["Just show up by 7, okay?", "7시까지만 와, 알았지?"]] },
  { id: 67, w: "take care of", p: "[teɪk ker əv] 테이크 케어 오브", m: "돌보다; 처리하다", ex: [["I'll take care of the bill.", "계산은 내가 처리할게."], ["She takes care of her little brother.", "걔는 남동생을 돌봐."]] },
  { id: 68, w: "come over", p: "[kʌm ˈoʊvər] 컴 오버", m: "(우리 집에) 오다, 건너오다", ex: [["Why don't you come over for dinner?", "저녁 먹으러 우리 집에 올래?"], ["My friends are coming over tonight.", "오늘 밤에 친구들이 우리 집에 와."]] },
  { id: 69, w: "get over", p: "[ɡet ˈoʊvər] 겟 오버", m: "극복하다, (병·이별에서) 회복하다", ex: [["It took me a while to get over the cold.", "감기 낫는 데 한참 걸렸어."], ["You'll get over it soon.", "곧 괜찮아질 거야."]] },
  { id: 70, w: "end up", p: "[end ʌp] 엔드 업", m: "결국 ~하게 되다", ex: [["We ended up ordering pizza.", "우리 결국 피자 시켰어."], ["I ended up staying home all day.", "결국 하루 종일 집에 있었어."]] },
  { id: 71, w: "make sense", p: "[meɪk sens] 메이크 센스", m: "말이 되다, 이해가 되다", ex: [["That makes sense.", "그거 말이 되네. (이해돼.)"], ["This sentence doesn't make sense.", "이 문장은 말이 안 돼."]] },
  { id: 72, w: "deserve", p: "[dɪˈzɜːrv] 디저브", m: "~을 받을 자격이 있다", ex: [["You deserve a break.", "넌 쉴 자격이 있어."], ["She deserves the award.", "그녀는 상 받을 만해."]] },
  { id: 73, w: "afford", p: "[əˈfɔːrd] 어포드", m: "~할 (금전적) 여유가 있다", ex: [["I can't afford a new car right now.", "지금은 새 차 살 여유가 없어."], ["Can we afford to eat out tonight?", "오늘 외식할 여유 될까?"]] },
  { id: 74, w: "annoying", p: "[əˈnɔɪɪŋ] 어노잉", m: "짜증나는, 성가신", ex: [["The noise is so annoying.", "그 소음 진짜 짜증나."], ["He can be annoying sometimes.", "걔 가끔 짜증나게 할 때 있어."]] },
  { id: 75, w: "awkward", p: "[ˈɔːkwərd] 어쿼드", m: "어색한, 곤란한", ex: [["There was an awkward silence.", "어색한 침묵이 흘렀어."], ["It was so awkward seeing my ex.", "전 애인을 마주쳐서 너무 어색했어."]] },
  { id: 76, w: "chilly", p: "[ˈtʃɪli] 칠리", m: "쌀쌀한", ex: [["It's a bit chilly today.", "오늘 좀 쌀쌀하네."], ["Take a jacket. It gets chilly at night.", "재킷 챙겨. 밤엔 쌀쌀해져."]] },
  { id: 77, w: "cozy", p: "[ˈkoʊzi] 코지", m: "아늑한, 포근한", ex: [["This cafe is so cozy.", "이 카페 진짜 아늑하다."], ["I love staying cozy at home on rainy days.", "비 오는 날엔 집에서 포근하게 있는 게 좋아."]] },
  { id: 78, w: "disappointed", p: "[ˌdɪsəˈpɔɪntɪd] 디서포인티드", m: "실망한", ex: [["I was disappointed with the movie.", "그 영화 실망스러웠어."], ["Don't be disappointed. There's always next time.", "실망하지 마. 다음 기회가 있잖아."]] },
  { id: 79, w: "fancy", p: "[ˈfænsi] 팬시", m: "고급스러운, 화려한", ex: [["We went to a fancy restaurant.", "우리 고급 레스토랑에 갔어."], ["You look fancy today! What's the occasion?", "오늘 쫙 빼입었네! 무슨 날이야?"]] },
  { id: 80, w: "spicy", p: "[ˈspaɪsi] 스파이시", m: "매운", ex: [["Is this dish spicy?", "이 음식 매워요?"], ["I can't handle spicy food.", "난 매운 거 잘 못 먹어."]] },
  { id: 81, w: "thirsty", p: "[ˈθɜːrsti] 써스티", m: "목마른", ex: [["I'm so thirsty. Let's get something to drink.", "목말라 죽겠어. 뭐 좀 마시러 가자."], ["This salty food makes me thirsty.", "이 짠 음식 때문에 목말라."]] },
  { id: 82, w: "dizzy", p: "[ˈdɪzi] 디지", m: "어지러운", ex: [["I feel dizzy when I stand up.", "일어나면 어지러워."], ["The ride made me dizzy.", "놀이기구 타고 어지러웠어."]] },
  { id: 83, w: "sore", p: "[sɔːr] 쏘어", m: "아픈, 쑤시는 (근육·목 등)", ex: [["I have a sore throat.", "목이 아파요. (인후통)"], ["My legs are sore from the workout.", "운동했더니 다리가 쑤셔."]] },
  { id: 84, w: "allergic", p: "[əˈlɜːrdʒɪk] 얼러직", m: "알레르기가 있는", ex: [["I'm allergic to peanuts.", "저 땅콩 알레르기 있어요."], ["Are you allergic to anything?", "알레르기 있는 거 있어요?"]] },
  { id: 85, w: "receipt", p: "[rɪˈsiːt] 리시트", m: "영수증", ex: [["Can I get a receipt, please?", "영수증 주시겠어요?"], ["Keep the receipt in case you need a refund.", "환불할 수도 있으니 영수증 챙겨놔."]] },
  { id: 86, w: "line", p: "[laɪn] 라인", m: "줄; 줄을 서다", ex: [["Is this the line for tickets?", "이게 티켓 줄인가요?"], ["We waited in line for an hour.", "우리 한 시간 동안 줄 섰어."]] },
  { id: 87, w: "traffic", p: "[ˈtræfɪk] 트래픽", m: "교통(량), 차량 정체", ex: [["There's heavy traffic this morning.", "오늘 아침 차가 엄청 막혀."], ["Sorry I'm late. The traffic was terrible.", "늦어서 미안. 차가 너무 막혔어."]] },
  { id: 88, w: "deadline", p: "[ˈdedlaɪn] 데드라인", m: "마감 기한", ex: [["The deadline is this Friday.", "마감이 이번 금요일이야."], ["I'm racing to meet the deadline.", "마감 맞추려고 달리는 중이야."]] },
  { id: 89, w: "day off", p: "[deɪ ɔːf] 데이 오프", m: "쉬는 날, 휴무", ex: [["Tomorrow is my day off.", "내일 나 쉬는 날이야."], ["I need a day off so badly.", "하루 쉬는 게 절실해."]] },
  { id: 90, w: "overtime", p: "[ˈoʊvərtaɪm] 오버타임", m: "야근, 초과 근무", ex: [["I worked overtime again last night.", "어젯밤에 또 야근했어."], ["Do you get paid for overtime?", "야근 수당 받아?"]] },
  { id: 91, w: "coworker", p: "[ˈkoʊwɜːrkər] 코워커", m: "직장 동료", ex: [["My coworkers are really nice.", "내 직장 동료들 진짜 좋아."], ["I'm having lunch with a coworker.", "동료랑 점심 먹는 중이야."]] },
  { id: 92, w: "errand", p: "[ˈerənd] 에런드", m: "심부름, 볼일", ex: [["I have to run some errands today.", "오늘 볼일 좀 봐야 해."], ["Can you do an errand for me?", "심부름 하나만 해줄래?"]] },
  { id: 93, w: "laundry", p: "[ˈlɔːndri] 런드리", m: "빨래, 세탁물", ex: [["I need to do the laundry today.", "오늘 빨래해야 해."], ["The laundry is piling up.", "빨랫감이 쌓여가고 있어."]] },
  { id: 94, w: "leftover", p: "[ˈleftoʊvər] 레프트오버", m: "남은 음식", ex: [["We had leftovers for lunch.", "점심으로 남은 음식 먹었어."], ["Can I take the leftovers home?", "남은 거 싸 갈 수 있을까요?"]] },
  { id: 95, w: "craving", p: "[ˈkreɪvɪŋ] 크레이빙", m: "(특정 음식이) 당김, 갈망", ex: [["I have a craving for chicken.", "치킨이 당겨."], ["I'm craving something sweet.", "단 게 먹고 싶어."]] },
  { id: 96, w: "split", p: "[splɪt] 스플릿", m: "나누다 (비용을 분담하다)", ex: [["Let's split the bill.", "계산은 나눠서 내자. (더치페이하자)"], ["We split the pizza in half.", "우리 피자 반씩 나눠 먹었어."]] },
  { id: 97, w: "to go", p: "[tu ɡoʊ] 투 고", m: "포장해서, 테이크아웃으로", ex: [["Can I get this to go?", "이거 포장해 주시겠어요?"], ["Two coffees to go, please.", "커피 두 잔 포장이요."]] },
  { id: 98, w: "refill", p: "[ˈriːfɪl] 리필", m: "리필; 다시 채우다", ex: [["Can I get a refill, please?", "리필 가능할까요?"], ["Refills are free here.", "여긴 리필이 공짜야."]] },
  { id: 99, w: "charger", p: "[ˈtʃɑːrdʒər] 차저", m: "충전기", ex: [["Did you bring your charger?", "충전기 가져왔어?"], ["Can I borrow your phone charger?", "폰 충전기 좀 빌릴 수 있을까?"]] },
  { id: 100, w: "outlet", p: "[ˈaʊtlet] 아웃렛", m: "콘센트", ex: [["Is there an outlet near here?", "이 근처에 콘센트 있나요?"], ["All the outlets in this cafe are taken.", "이 카페 콘센트 자리 다 찼어."]] },
  { id: 101, w: "luggage", p: "[ˈlʌɡɪdʒ] 러기지", m: "짐, 수하물", ex: [["How much luggage do you have?", "짐이 얼마나 돼?"], ["My luggage didn't arrive!", "제 짐이 안 왔어요!"]] },
  { id: 102, w: "round trip", p: "[raʊnd trɪp] 라운드 트립", m: "왕복 (여행·표)", ex: [["A round trip ticket to Busan, please.", "부산 왕복표 한 장 주세요."], ["How much is a round trip?", "왕복은 얼마예요?"]] },
  { id: 103, w: "book", p: "[bʊk] 북", m: "예약하다", ex: [["I booked a hotel for two nights.", "호텔 2박 예약했어."], ["Should we book in advance?", "미리 예약해야 할까?"]] },
  { id: 104, w: "check in", p: "[tʃek ɪn] 체크 인", m: "체크인하다, 탑승 수속하다", ex: [["What time can we check in?", "몇 시에 체크인할 수 있나요?"], ["I checked in online already.", "온라인으로 이미 체크인했어."]] },
  { id: 105, w: "souvenir", p: "[ˌsuːvəˈnɪr] 수버니어", m: "기념품", ex: [["I bought some souvenirs for my family.", "가족들 주려고 기념품 좀 샀어."], ["This is a souvenir from my trip to Japan.", "이거 일본 여행 기념품이야."]] },
  { id: 106, w: "forecast", p: "[ˈfɔːrkæst] 포어캐스트", m: "(날씨) 예보", ex: [["What's the forecast for tomorrow?", "내일 일기예보 어때?"], ["The forecast says it'll rain.", "예보에서 비 온대."]] },
  { id: 107, w: "humid", p: "[ˈhjuːmɪd] 휴미드", m: "습한", ex: [["It's so humid today.", "오늘 진짜 습하다."], ["Korean summers are hot and humid.", "한국 여름은 덥고 습해."]] },
  { id: 108, w: "pour", p: "[pɔːr] 포어", m: "(비가) 퍼붓다; 따르다", ex: [["It's pouring outside!", "밖에 비 퍼붓고 있어!"], ["Could you pour me some water?", "물 좀 따라 줄래?"]] },
  { id: 109, w: "freezing", p: "[ˈfriːzɪŋ] 프리징", m: "꽁꽁 얼게 추운", ex: [["It's freezing out here!", "여기 밖 얼어 죽겠어!"], ["My hands are freezing.", "손이 꽁꽁 얼었어."]] },
  { id: 110, w: "get off", p: "[ɡet ɔːf] 겟 오프", m: "(버스·지하철에서) 내리다; 퇴근하다", ex: [["We get off at the next stop.", "우리 다음 정거장에서 내려."], ["What time do you get off work?", "몇 시에 퇴근해?"]] },
  { id: 111, w: "transfer", p: "[ˈtrænsfɜːr] 트랜스퍼", m: "환승하다; 옮기다", ex: [["Transfer to Line 2 at City Hall.", "시청역에서 2호선으로 환승하세요."], ["Do I need to transfer?", "환승해야 하나요?"]] },
  { id: 112, w: "fare", p: "[fer] 페어", m: "(교통) 요금", ex: [["How much is the bus fare?", "버스 요금이 얼마예요?"], ["Taxi fares went up again.", "택시 요금 또 올랐어."]] },
  { id: 113, w: "shortcut", p: "[ˈʃɔːrtkʌt] 쇼트컷", m: "지름길", ex: [["I know a shortcut to the station.", "역까지 가는 지름길 알아."], ["Let's take a shortcut through the park.", "공원 가로질러서 지름길로 가자."]] },
  { id: 114, w: "on time", p: "[ɑːn taɪm] 온 타임", m: "제시간에, 정각에", ex: [["The train arrived on time.", "기차가 제시간에 도착했어."], ["Please be on time tomorrow.", "내일은 제시간에 와 줘."]] },
  { id: 115, w: "in a row", p: "[ɪn ə roʊ] 인 어 로우", m: "연속으로", ex: [["It rained three days in a row.", "3일 연속으로 비가 왔어."], ["I've studied English 10 days in a row!", "나 10일 연속 영어 공부했어!"]] },
  { id: 116, w: "run out of", p: "[rʌn aʊt əv] 런 아웃 오브", m: "~이 다 떨어지다", ex: [["We ran out of milk.", "우유가 다 떨어졌어."], ["My phone is running out of battery.", "폰 배터리가 다 돼 가."]] },
  { id: 117, w: "in the middle of", p: "[ɪn ðə ˈmɪdl əv] 인 더 미들 오브", m: "~하는 중인, 한가운데인", ex: [["I'm in the middle of something. Can I call you back?", "지금 뭐 하는 중이라, 다시 전화해도 될까?"], ["He left in the middle of the movie.", "걔 영화 보다가 중간에 나갔어."]] },
  { id: 118, w: "by the way", p: "[baɪ ðə weɪ] 바이 더 웨이", m: "그건 그렇고, 참", ex: [["By the way, did you hear the news?", "그건 그렇고, 그 소식 들었어?"], ["By the way, I love your shoes.", "참, 네 신발 진짜 예쁘다."]] },
  { id: 119, w: "kind of", p: "[kaɪnd əv] 카인드 오브", m: "약간, 어느 정도 (= 좀)", ex: [["I'm kind of tired today.", "나 오늘 좀 피곤해."], ["It's kind of complicated.", "그게 좀 복잡해."]] },
  { id: 120, w: "no wonder", p: "[noʊ ˈwʌndər] 노 원더", m: "어쩐지, 그럴 만하다", ex: [["No wonder you're tired. You barely slept!", "어쩐지 피곤하더라. 너 거의 못 잤잖아!"], ["No wonder this place is always crowded.", "어쩐지 여기 항상 붐비더라."]] },
  { id: 121, w: "give it a try", p: "[ɡɪv ɪt ə traɪ] 기브 잇 어 트라이", m: "한번 해보다", ex: [["Just give it a try. You might like it.", "그냥 한번 해봐. 마음에 들지도 몰라."], ["I'll give it a try this weekend.", "이번 주말에 한번 해볼게."]] },
  { id: 122, w: "take a break", p: "[teɪk ə breɪk] 테이크 어 브레이크", m: "잠깐 쉬다", ex: [["Let's take a break for 10 minutes.", "10분만 쉬자."], ["You've been working all day. Take a break.", "너 하루 종일 일했잖아. 좀 쉬어."]] },
  { id: 123, w: "calm down", p: "[kɑːm daʊn] 캄 다운", m: "진정하다", ex: [["Calm down and tell me what happened.", "진정하고 무슨 일인지 말해봐."], ["It took me a while to calm down.", "진정하는 데 한참 걸렸어."]] },
  { id: 124, w: "cheer up", p: "[tʃɪr ʌp] 치어 업", m: "기운 내다, 기운 나게 하다", ex: [["Cheer up! Tomorrow is another day.", "기운 내! 내일은 또 내일의 해가 떠."], ["This song always cheers me up.", "이 노래 들으면 항상 기운이 나."]] },
  { id: 125, w: "hold on", p: "[hoʊld ɑːn] 홀드 온", m: "잠깐 기다리다", ex: [["Hold on a second. I'll be right back.", "잠깐만 기다려. 금방 올게."], ["Hold on, let me check my schedule.", "잠깐만, 일정 좀 확인해볼게."]] },
  { id: 126, w: "check out", p: "[tʃek aʊt] 체크 아웃", m: "확인해보다; (호텔) 체크아웃하다", ex: [["Check out this new cafe!", "이 새로 생긴 카페 한번 봐봐!"], ["We need to check out by 11.", "우리 11시까지 체크아웃해야 해."]] },
  { id: 127, w: "find out", p: "[faɪnd aʊt] 파인드 아웃", m: "알아내다, 알게 되다", ex: [["I just found out the news.", "방금 그 소식 알게 됐어."], ["How did you find out about this place?", "여기 어떻게 알았어?"]] },
  { id: 128, w: "turn out", p: "[tɜːrn aʊt] 턴 아웃", m: "알고 보니 ~이다, 결과가 ~로 나오다", ex: [["It turned out to be a great day.", "알고 보니 정말 좋은 하루였어."], ["Everything turned out fine.", "결국 다 잘 됐어."]] },
  { id: 129, w: "give up", p: "[ɡɪv ʌp] 기브 업", m: "포기하다", ex: [["Don't give up! You're almost there.", "포기하지 마! 거의 다 왔어."], ["I gave up drinking coffee at night.", "밤에 커피 마시는 거 끊었어."]] },
  { id: 130, w: "put off", p: "[pʊt ɔːf] 풋 오프", m: "미루다, 연기하다", ex: [["Stop putting off your homework.", "숙제 그만 미뤄."], ["The meeting was put off until next week.", "회의가 다음 주로 미뤄졌어."]] },
  { id: 131, w: "look up", p: "[lʊk ʌp] 룩 업", m: "(사전·인터넷에서) 찾아보다", ex: [["Let me look it up on my phone.", "폰으로 찾아볼게."], ["I looked up the word in the dictionary.", "그 단어 사전에서 찾아봤어."]] },
  { id: 132, w: "throw away", p: "[θroʊ əˈweɪ] 쓰로우 어웨이", m: "버리다", ex: [["Did you throw away the receipt?", "영수증 버렸어?"], ["Don't throw away the box yet.", "그 상자 아직 버리지 마."]] },
  { id: 133, w: "turn down", p: "[tɜːrn daʊn] 턴 다운", m: "거절하다; (소리·온도) 줄이다", ex: [["I had to turn down the offer.", "그 제안을 거절해야 했어."], ["Can you turn down the music?", "음악 소리 좀 줄여줄래?"]] },
  { id: 134, w: "try on", p: "[traɪ ɑːn] 트라이 온", m: "(옷을) 입어보다", ex: [["Can I try this on?", "이거 입어봐도 돼요?"], ["Try on both sizes and see.", "두 사이즈 다 입어보고 정해."]] },
  { id: 135, w: "take off", p: "[teɪk ɔːf] 테이크 오프", m: "이륙하다; (옷을) 벗다", ex: [["The plane takes off at 9.", "비행기가 9시에 이륙해."], ["Please take off your shoes here.", "여기서는 신발을 벗어주세요."]] },
  { id: 136, w: "fill out", p: "[fɪl aʊt] 필 아웃", m: "(서류를) 작성하다", ex: [["Please fill out this form.", "이 양식을 작성해 주세요."], ["I filled out the application online.", "신청서를 온라인으로 작성했어."]] },
  { id: 137, w: "sign up", p: "[saɪn ʌp] 사인 업", m: "가입하다, 등록하다", ex: [["I signed up for a yoga class.", "요가 수업 등록했어."], ["Sign up now and get a discount.", "지금 가입하면 할인받아요."]] },
  { id: 138, w: "set up", p: "[set ʌp] 셋 업", m: "설치하다, 준비하다", ex: [["Can you help me set up my new phone?", "새 폰 설정하는 것 좀 도와줄래?"], ["We set up the meeting for Tuesday.", "회의를 화요일로 잡았어."]] },
  { id: 139, w: "catch up", p: "[kætʃ ʌp] 캐치 업", m: "밀린 얘기를 나누다; 따라잡다", ex: [["Let's catch up over coffee soon!", "조만간 커피 마시면서 밀린 얘기 하자!"], ["I need to catch up on sleep.", "밀린 잠 좀 자야 해."]] },
  { id: 140, w: "drop off", p: "[drɑːp ɔːf] 드랍 오프", m: "(사람·물건을) 내려주다, 갖다주다", ex: [["I'll drop you off at the station.", "역에 내려줄게."], ["Can you drop off this package for me?", "이 소포 좀 갖다줄 수 있어?"]] },
  { id: 141, w: "get together", p: "[ɡet təˈɡeðər] 겟 투게더", m: "모이다, 만나다", ex: [["Let's get together this Saturday.", "이번 토요일에 모이자."], ["We get together once a month.", "우리 한 달에 한 번 모여."]] },
  { id: 142, w: "sleep in", p: "[sliːp ɪn] 슬립 인", m: "늦잠 자다 (일부러)", ex: [["I love sleeping in on Sundays.", "일요일에 늦잠 자는 게 너무 좋아."], ["Let's sleep in tomorrow. No plans!", "내일은 늦잠 자자. 약속 없음!"]] },
  { id: 143, w: "stay up", p: "[steɪ ʌp] 스테이 업", m: "안 자고 깨어 있다", ex: [["I stayed up late watching a drama.", "드라마 보느라 늦게까지 안 잤어."], ["Don't stay up too late.", "너무 늦게까지 깨어 있지 마."]] },
  { id: 144, w: "move in", p: "[muːv ɪn] 무브 인", m: "이사 들어오다", ex: [["We just moved in last week.", "우리 지난주에 막 이사 왔어."], ["When are you moving in?", "언제 이사 들어와?"]] },
  { id: 145, w: "eat out", p: "[iːt aʊt] 잇 아웃", m: "외식하다", ex: [["Let's eat out tonight.", "오늘 저녁은 외식하자."], ["We eat out about twice a week.", "우리 일주일에 두 번 정도 외식해."]] },
  { id: 146, w: "hang up", p: "[hæŋ ʌp] 행 업", m: "전화를 끊다", ex: [["Don't hang up yet!", "아직 끊지 마!"], ["She hung up on me!", "걔가 내 전화를 뚝 끊어버렸어!"]] },
  { id: 147, w: "call back", p: "[kɔːl bæk] 콜 백", m: "다시 전화하다", ex: [["Can I call you back in 10 minutes?", "10분 뒤에 다시 전화해도 될까?"], ["He never called me back.", "걔 나한테 다시 전화 안 했어."]] },
  { id: 148, w: "reply", p: "[rɪˈplaɪ] 리플라이", m: "답장하다; 답장", ex: [["Sorry for the late reply.", "답장 늦어서 미안."], ["She hasn't replied to my message yet.", "걔 아직 내 메시지에 답장 안 했어."]] },
  { id: 149, w: "charge", p: "[tʃɑːrdʒ] 차지", m: "충전하다; (요금을) 청구하다", ex: [["I need to charge my phone.", "폰 충전해야 해."], ["They charged me twice!", "나한테 요금이 두 번 청구됐어!"]] },
  { id: 150, w: "cost", p: "[kɔːst] 코스트", m: "(비용이) 들다; 비용", ex: [["How much does it cost?", "이거 얼마예요?"], ["It cost me a fortune.", "돈이 어마어마하게 들었어."]] },
  { id: 151, w: "proud", p: "[praʊd] 프라우드", m: "자랑스러운", ex: [["I'm so proud of you!", "네가 정말 자랑스러워!"], ["You should be proud of yourself.", "넌 스스로를 자랑스러워해도 돼."]] },
  { id: 152, w: "relieved", p: "[rɪˈliːvd] 릴리브드", m: "안도한, 마음이 놓인", ex: [["I'm so relieved to hear that.", "그 말 들으니 정말 마음이 놓인다."], ["She looked relieved after the test.", "시험 끝나고 걔 안도한 표정이었어."]] },
  { id: 153, w: "frustrated", p: "[ˈfrʌstreɪtɪd] 프러스트레이티드", m: "답답한, 좌절한", ex: [["I get frustrated when the Wi-Fi is slow.", "와이파이 느리면 답답해."], ["Don't get frustrated. Take it slow.", "답답해하지 마. 천천히 해."]] },
  { id: 154, w: "overwhelmed", p: "[ˌoʊvərˈwelmd] 오버웰름드", m: "(일·감정에) 압도된, 벅찬", ex: [["I'm overwhelmed with work this week.", "이번 주 일이 너무 많아서 정신없어."], ["She was overwhelmed by the surprise party.", "걔는 깜짝 파티에 감격했어."]] },
  { id: 155, w: "motivated", p: "[ˈmoʊtɪveɪtɪd] 모티베이티드", m: "의욕이 넘치는", ex: [["I feel so motivated today!", "오늘 의욕이 넘쳐!"], ["What keeps you motivated?", "넌 어떻게 의욕을 유지해?"]] },
  { id: 156, w: "bored", p: "[bɔːrd] 보어드", m: "지루한, 심심한", ex: [["I'm so bored. Let's do something.", "너무 심심해. 뭐라도 하자."], ["The kids got bored quickly.", "애들이 금방 지루해했어."]] },
  { id: 157, w: "thrilled", p: "[θrɪld] 쓰릴드", m: "아주 신난, 매우 기쁜", ex: [["I'm thrilled about the trip!", "여행 갈 생각에 완전 신나!"], ["She was thrilled with the gift.", "걔 선물 받고 엄청 좋아했어."]] },
  { id: 158, w: "scared", p: "[skerd] 스케어드", m: "무서운, 겁먹은", ex: [["I'm scared of heights.", "나 높은 데 무서워해."], ["Don't be scared. I'm right here.", "무서워하지 마. 내가 여기 있잖아."]] },
  { id: 159, w: "anxious", p: "[ˈæŋkʃəs] 앵셔스", m: "불안한, 초조한", ex: [["I feel anxious before interviews.", "면접 전에는 불안해."], ["There's nothing to be anxious about.", "불안해할 거 하나도 없어."]] },
  { id: 160, w: "confident", p: "[ˈkɑːnfɪdənt] 칸피던트", m: "자신 있는", ex: [["Be confident! You've got this.", "자신감 가져! 넌 할 수 있어."], ["I'm confident about the result.", "결과에 자신 있어."]] },
  { id: 161, w: "generous", p: "[ˈdʒenərəs] 제너러스", m: "너그러운, 잘 베푸는", ex: [["That's very generous of you.", "정말 너그러우시네요. (감사해요)"], ["He's generous with his time.", "걔는 시간을 아낌없이 내줘."]] },
  { id: 162, w: "polite", p: "[pəˈlaɪt] 폴라이트", m: "예의 바른, 공손한", ex: [["He's always polite to everyone.", "걔는 모두에게 항상 예의 발라."], ["It's polite to say thank you.", "고맙다고 말하는 게 예의야."]] },
  { id: 163, w: "rude", p: "[ruːd] 루드", m: "무례한", ex: [["That was so rude of him.", "걔 진짜 무례했어."], ["I don't want to be rude, but...", "무례하게 굴고 싶진 않지만..."]] },
  { id: 164, w: "picky", p: "[ˈpɪki] 피키", m: "까다로운 (특히 음식·취향)", ex: [["I'm a picky eater.", "나 편식이 심해."], ["She's picky about coffee.", "걔는 커피에 까다로워."]] },
  { id: 165, w: "outgoing", p: "[ˈaʊtɡoʊɪŋ] 아웃고잉", m: "외향적인, 사교적인", ex: [["My sister is really outgoing.", "우리 언니는 정말 외향적이야."], ["You're more outgoing than I thought!", "너 생각보다 사교적이네!"]] },
  { id: 166, w: "shy", p: "[ʃaɪ] 샤이", m: "수줍은, 부끄러워하는", ex: [["Don't be shy. Come join us!", "부끄러워하지 말고 와서 같이 해!"], ["I was shy as a kid.", "나 어릴 때 수줍음 많았어."]] },
  { id: 167, w: "talkative", p: "[ˈtɔːkətɪv] 토커티브", m: "수다스러운, 말이 많은", ex: [["He gets talkative after coffee.", "걔 커피 마시면 말 많아져."], ["She's not very talkative in the morning.", "걔는 아침엔 말이 별로 없어."]] },
  { id: 168, w: "reliable", p: "[rɪˈlaɪəbl] 릴라이어블", m: "믿을 만한, 의지할 수 있는", ex: [["He's the most reliable person I know.", "걔는 내가 아는 사람 중 제일 믿을 만해."], ["Is this information reliable?", "이 정보 믿을 만해?"]] },
  { id: 169, w: "selfish", p: "[ˈselfɪʃ] 셀피쉬", m: "이기적인", ex: [["Don't be so selfish.", "너무 이기적으로 굴지 마."], ["It was selfish of me. I'm sorry.", "내가 이기적이었어. 미안해."]] },
  { id: 170, w: "down-to-earth", p: "[daʊn tu ɜːrθ] 다운 투 어스", m: "소탈한, 현실적인", ex: [["She's famous but very down-to-earth.", "걔는 유명한데도 진짜 소탈해."], ["I like how down-to-earth he is.", "걔가 소탈해서 좋아."]] },
  { id: 171, w: "fridge", p: "[frɪdʒ] 프리지", m: "냉장고", ex: [["There's nothing in the fridge.", "냉장고에 아무것도 없어."], ["Put the leftovers in the fridge.", "남은 음식 냉장고에 넣어놔."]] },
  { id: 172, w: "microwave", p: "[ˈmaɪkrəweɪv] 마이크로웨이브", m: "전자레인지; 전자레인지에 돌리다", ex: [["Just microwave it for 2 minutes.", "전자레인지에 2분만 돌려."], ["Is this container microwave-safe?", "이 용기 전자레인지에 돌려도 돼?"]] },
  { id: 173, w: "trash", p: "[træʃ] 트래쉬", m: "쓰레기", ex: [["Can you take out the trash?", "쓰레기 좀 내다 버려줄래?"], ["Where's the trash can?", "쓰레기통이 어디예요?"]] },
  { id: 174, w: "bill", p: "[bɪl] 빌", m: "청구서, 계산서", ex: [["Can we get the bill, please?", "계산서 주시겠어요?"], ["The electricity bill went up this month.", "이번 달 전기요금 올랐어."]] },
  { id: 175, w: "discount", p: "[ˈdɪskaʊnt] 디스카운트", m: "할인", ex: [["Is there a student discount?", "학생 할인 있나요?"], ["I got it at a 30% discount.", "이거 30% 할인받아서 샀어."]] },
  { id: 176, w: "coupon", p: "[ˈkuːpɑːn] 쿠판", m: "쿠폰", ex: [["I have a coupon for this store.", "이 가게 쿠폰 있어."], ["Don't forget to use your coupon.", "쿠폰 쓰는 거 잊지 마."]] },
  { id: 177, w: "cashier", p: "[kæˈʃɪr] 캐셔", m: "계산원, 계산대", ex: [["Please pay at the cashier.", "계산대에서 계산해 주세요."], ["The cashier was really friendly.", "계산원이 진짜 친절했어."]] },
  { id: 178, w: "aisle", p: "[aɪl] 아일", m: "통로, (매장) 코너", ex: [["The snacks are in aisle 3.", "과자는 3번 통로에 있어요."], ["Excuse me, which aisle is the shampoo in?", "실례지만 샴푸는 몇 번 코너에 있나요?"]] },
  { id: 179, w: "shelf", p: "[ʃelf] 쉘프", m: "선반", ex: [["It's on the top shelf.", "맨 위 선반에 있어."], ["The shelves are almost empty.", "선반이 거의 비었네."]] },
  { id: 180, w: "cart", p: "[kɑːrt] 카트", m: "카트, 장바구니", ex: [["Grab a cart on the way in.", "들어가면서 카트 하나 끌고 와."], ["I added it to my cart online.", "온라인 장바구니에 담아놨어."]] },
  { id: 181, w: "pharmacy", p: "[ˈfɑːrməsi] 파머시", m: "약국", ex: [["Is there a pharmacy nearby?", "근처에 약국 있나요?"], ["The pharmacy closes at 8.", "약국은 8시에 닫아."]] },
  { id: 182, w: "prescription", p: "[prɪˈskrɪpʃn] 프리스크립션", m: "처방전", ex: [["You need a prescription for this medicine.", "이 약은 처방전이 필요해요."], ["The doctor gave me a prescription.", "의사가 처방전을 줬어."]] },
  { id: 183, w: "painkiller", p: "[ˈpeɪnkɪlər] 페인킬러", m: "진통제", ex: [["Do you have any painkillers?", "진통제 있어?"], ["I took a painkiller for my headache.", "두통 때문에 진통제 먹었어."]] },
  { id: 184, w: "symptom", p: "[ˈsɪmptəm] 심텀", m: "증상", ex: [["What are your symptoms?", "증상이 어떻게 되세요?"], ["The symptoms went away after a day.", "증상이 하루 지나니까 사라졌어."]] },
  { id: 185, w: "checkup", p: "[ˈtʃekʌp] 체크업", m: "건강검진", ex: [["I have a checkup next week.", "다음 주에 건강검진 있어."], ["You should get a regular checkup.", "정기 검진 받는 게 좋아."]] },
  { id: 186, w: "dentist", p: "[ˈdentɪst] 덴티스트", m: "치과, 치과의사", ex: [["I hate going to the dentist.", "치과 가는 거 너무 싫어."], ["I have a dentist appointment at 4.", "4시에 치과 예약 있어."]] },
  { id: 187, w: "haircut", p: "[ˈherkʌt] 헤어컷", m: "이발, 머리 자르기", ex: [["I need a haircut.", "머리 잘라야 해."], ["Nice haircut! It suits you.", "머리 잘 잘랐네! 잘 어울려."]] },
  { id: 188, w: "salon", p: "[səˈlɑːn] 설란", m: "미용실", ex: [["I'm going to the salon tomorrow.", "내일 미용실 가."], ["This salon is always fully booked.", "이 미용실은 항상 예약이 꽉 차."]] },
  { id: 189, w: "gym", p: "[dʒɪm] 짐", m: "헬스장", ex: [["I go to the gym every morning.", "매일 아침 헬스장 가."], ["See you at the gym!", "헬스장에서 봐!"]] },
  { id: 190, w: "membership", p: "[ˈmembərʃɪp] 멤버십", m: "회원권, 멤버십", ex: [["How much is the gym membership?", "헬스장 회원권 얼마예요?"], ["My membership expires this month.", "내 멤버십 이번 달에 끝나."]] },
  { id: 191, w: "appetizer", p: "[ˈæpɪtaɪzər] 애피타이저", m: "애피타이저, 전채 요리", ex: [["Should we order some appetizers?", "애피타이저 좀 시킬까?"], ["The appetizer was better than the main.", "애피타이저가 메인보다 맛있었어."]] },
  { id: 192, w: "dessert", p: "[dɪˈzɜːrt] 디저트", m: "디저트, 후식", ex: [["There's always room for dessert!", "디저트 배는 따로 있지!"], ["What do you have for dessert?", "디저트는 뭐가 있나요?"]] },
  { id: 193, w: "beverage", p: "[ˈbevərɪdʒ] 베버리지", m: "음료", ex: [["Would you like a beverage with that?", "음료도 같이 드릴까요?"], ["Cold beverages are in the back.", "차가운 음료는 뒤쪽에 있어요."]] },
  { id: 194, w: "straw", p: "[strɔː] 스트로", m: "빨대", ex: [["Can I get a straw, please?", "빨대 좀 주시겠어요?"], ["They don't give out plastic straws here.", "여긴 플라스틱 빨대 안 줘."]] },
  { id: 195, w: "napkin", p: "[ˈnæpkɪn] 냅킨", m: "냅킨, 휴지", ex: [["Could I get some napkins?", "냅킨 좀 주시겠어요?"], ["He wrote his number on a napkin.", "걔가 냅킨에 번호를 적어줬어."]] },
  { id: 196, w: "chopsticks", p: "[ˈtʃɑːpstɪks] 찹스틱스", m: "젓가락", ex: [["Can you use chopsticks?", "젓가락 쓸 줄 알아?"], ["I dropped my chopsticks.", "젓가락 떨어뜨렸어."]] },
  { id: 197, w: "well-done", p: "[wel dʌn] 웰 던", m: "(고기를) 완전히 익힌; 잘했어", ex: [["I'd like my steak well-done.", "스테이크 완전히 익혀 주세요."], ["Well done! I knew you could do it.", "잘했어! 네가 해낼 줄 알았어."]] },
  { id: 198, w: "tip", p: "[tɪp] 팁", m: "팁; 조언, 꿀팁", ex: [["Should we leave a tip?", "팁 남겨야 하나?"], ["Any tips for learning English?", "영어 공부 꿀팁 있어?"]] },
  { id: 199, w: "flavor", p: "[ˈfleɪvər] 플레이버", m: "맛, 풍미", ex: [["What flavor do you want?", "무슨 맛으로 할래?"], ["This has a unique flavor.", "이거 맛이 독특하네."]] },
  { id: 200, w: "bite", p: "[baɪt] 바이트", m: "한 입; 물다; 간단히 먹기", ex: [["Can I have a bite?", "한 입만 먹어도 돼?"], ["Let's grab a bite before the movie.", "영화 보기 전에 간단히 뭐 좀 먹자."]] },
  { id: 201, w: "I mean", p: "[aɪ miːn] 아이 민", m: "그러니까, 내 말은", ex: [["I mean, it's not bad, but...", "그러니까, 나쁘진 않은데..."], ["She's nice. I mean, really nice.", "걔 착해. 내 말은, 진짜 착하다고."]] },
  { id: 202, w: "anyway", p: "[ˈeniweɪ] 애니웨이", m: "어쨌든, 아무튼", ex: [["Anyway, let's get back to work.", "아무튼, 다시 일하자."], ["It was raining, but we went anyway.", "비가 왔지만 어쨌든 우린 갔어."]] },
  { id: 203, w: "seriously", p: "[ˈsɪriəsli] 시리어슬리", m: "진심으로, 진짜로", ex: [["Seriously? That's amazing!", "진짜? 대박이다!"], ["I'm seriously considering moving.", "이사 가는 거 진지하게 고민 중이야."]] },
  { id: 204, w: "exactly", p: "[ɪɡˈzæktli] 이그잭틀리", m: "정확히; 바로 그거야", ex: [["That's exactly what I meant.", "내 말이 바로 그거야."], ["Where exactly are we going?", "우리 정확히 어디 가는 거야?"]] },
  { id: 205, w: "probably", p: "[ˈprɑːbəbli] 프라버블리", m: "아마도", ex: [["I'll probably stay home tonight.", "오늘 밤엔 아마 집에 있을 거야."], ["It's probably going to rain.", "아마 비 올 것 같아."]] },
  { id: 206, w: "hopefully", p: "[ˈhoʊpfəli] 호프풀리", m: "바라건대, 잘하면", ex: [["Hopefully, the weather will be nice.", "날씨가 좋았으면 좋겠다."], ["Hopefully I'll see you next week!", "다음 주에 볼 수 있으면 좋겠어!"]] },
  { id: 207, w: "unfortunately", p: "[ʌnˈfɔːrtʃənətli] 언포츄너틀리", m: "안타깝게도, 아쉽게도", ex: [["Unfortunately, the tickets are sold out.", "아쉽게도 표가 매진됐어."], ["Unfortunately, I can't make it.", "안타깝지만 나 못 가."]] },
  { id: 208, w: "apparently", p: "[əˈpærəntli] 어패런틀리", m: "듣자 하니, 보아하니", ex: [["Apparently, they broke up.", "듣자 하니 걔네 헤어졌대."], ["Apparently it's the best place in town.", "보아하니 거기가 이 동네 최고래."]] },
  { id: 209, w: "obviously", p: "[ˈɑːbviəsli] 아비어슬리", m: "분명히, 누가 봐도", ex: [["He's obviously tired.", "걔 누가 봐도 피곤해 보여."], ["Obviously, I was wrong.", "분명히 내가 틀렸었어."]] },
  { id: 210, w: "basically", p: "[ˈbeɪsɪkli] 베이시클리", m: "기본적으로, 한마디로", ex: [["Basically, we have two options.", "한마디로 우리한텐 두 가지 선택지가 있어."], ["It's basically the same thing.", "그거 기본적으로 같은 거야."]] },
  { id: 211, w: "departure", p: "[dɪˈpɑːrtʃər] 디파처", m: "출발", ex: [["What's the departure time?", "출발 시간이 언제예요?"], ["Be at the gate 30 minutes before departure.", "출발 30분 전까지 게이트로 오세요."]] },
  { id: 212, w: "arrival", p: "[əˈraɪvl] 어라이벌", m: "도착", ex: [["The arrival time is 3 p.m.", "도착 시간은 오후 3시야."], ["I'll text you upon arrival.", "도착하면 문자할게."]] },
  { id: 213, w: "boarding pass", p: "[ˈbɔːrdɪŋ pæs] 보딩 패스", m: "탑승권", ex: [["May I see your boarding pass?", "탑승권 보여주시겠어요?"], ["I saved my boarding pass on my phone.", "탑승권 폰에 저장해놨어."]] },
  { id: 214, w: "aisle seat", p: "[aɪl siːt] 아일 시트", m: "통로 쪽 좌석", ex: [["I'd prefer an aisle seat, please.", "통로 쪽 좌석으로 부탁드려요."], ["Aisle seats are easier for the bathroom.", "통로 좌석이 화장실 가기 편해."]] },
  { id: 215, w: "window seat", p: "[ˈwɪndoʊ siːt] 윈도우 시트", m: "창가 좌석", ex: [["Can I get a window seat?", "창가 좌석으로 될까요?"], ["I always pick the window seat for the view.", "난 경치 때문에 항상 창가 자리 골라."]] },
  { id: 216, w: "customs", p: "[ˈkʌstəmz] 커스텀즈", m: "세관", ex: [["Do you have anything to declare at customs?", "세관에 신고할 물품 있나요?"], ["It took forever to get through customs.", "세관 통과하는 데 한참 걸렸어."]] },
  { id: 217, w: "exchange", p: "[ɪksˈtʃeɪndʒ] 익스체인지", m: "환전하다; 교환하다", ex: [["Where can I exchange money?", "어디서 환전할 수 있나요?"], ["Can I exchange this for a bigger size?", "이거 더 큰 사이즈로 교환할 수 있을까요?"]] },
  { id: 218, w: "destination", p: "[ˌdestɪˈneɪʃn] 데스티네이션", m: "목적지", ex: [["What's your final destination?", "최종 목적지가 어디예요?"], ["We arrived at our destination at noon.", "우리는 정오에 목적지에 도착했어."]] },
  { id: 219, w: "sightseeing", p: "[ˈsaɪtsiːɪŋ] 사이트시잉", m: "관광", ex: [["Let's go sightseeing tomorrow.", "내일 관광하러 가자."], ["We did some sightseeing downtown.", "우리 시내에서 관광 좀 했어."]] },
  { id: 220, w: "itinerary", p: "[aɪˈtɪnəreri] 아이티너레리", m: "여행 일정(표)", ex: [["I'll send you the itinerary.", "여행 일정표 보내줄게."], ["Our itinerary is packed!", "우리 일정 꽉 찼어!"]] },
  { id: 221, w: "get married", p: "[ɡet ˈmærid] 겟 매리드", m: "결혼하다", ex: [["They're getting married next month.", "걔네 다음 달에 결혼해."], ["When did you get married?", "언제 결혼하셨어요?"]] },
  { id: 222, w: "break up", p: "[breɪk ʌp] 브레이크 업", m: "헤어지다", ex: [["Did you hear they broke up?", "걔네 헤어졌다는 거 들었어?"], ["We broke up last year.", "우리 작년에 헤어졌어."]] },
  { id: 223, w: "ask out", p: "[æsk aʊt] 애스크 아웃", m: "데이트 신청하다", ex: [["He finally asked her out!", "걔가 드디어 데이트 신청했대!"], ["I'm too nervous to ask him out.", "데이트 신청하기엔 너무 떨려."]] },
  { id: 224, w: "have a crush on", p: "[hæv ə krʌʃ ɑːn] 해브 어 크러쉬 온", m: "~에게 반하다, 짝사랑하다", ex: [["I had a crush on him in high school.", "고등학교 때 걔 짝사랑했어."], ["She has a crush on someone at work.", "걔 회사에 좋아하는 사람 있대."]] },
  { id: 225, w: "keep in touch", p: "[kiːp ɪn tʌtʃ] 킵 인 터치", m: "연락하고 지내다", ex: [["Let's keep in touch!", "계속 연락하고 지내자!"], ["We kept in touch after college.", "우리 대학 졸업하고도 연락하고 지냈어."]] },
  { id: 226, w: "make it", p: "[meɪk ɪt] 메이크 잇", m: "시간 맞춰 가다; 해내다", ex: [["Sorry, I can't make it tonight.", "미안, 오늘 밤엔 못 가."], ["You made it! Congrats!", "네가 해냈어! 축하해!"]] },
  { id: 227, w: "hang in there", p: "[hæŋ ɪn ðer] 행 인 데어", m: "조금만 버텨, 힘내", ex: [["Hang in there. It's almost Friday.", "조금만 버텨. 금요일 다 왔어."], ["I know it's hard, but hang in there.", "힘든 거 알아, 그래도 버텨봐."]] },
  { id: 228, w: "it depends", p: "[ɪt dɪˈpendz] 잇 디펜즈", m: "상황에 따라 달라", ex: [["\"Are you free this weekend?\" \"It depends.\"", "\"주말에 시간 돼?\" \"상황 봐서.\""], ["It depends on the weather.", "날씨에 따라 달라."]] },
  { id: 229, w: "no big deal", p: "[noʊ bɪɡ diːl] 노 빅 딜", m: "별일 아니야", ex: [["Don't worry. It's no big deal.", "걱정 마. 별일 아니야."], ["It was no big deal at all.", "전혀 큰일 아니었어."]] },
  { id: 230, w: "my bad", p: "[maɪ bæd] 마이 배드", m: "내 잘못이야, 미안", ex: [["Oh, my bad. I forgot to call.", "아 미안, 전화하는 거 깜빡했어."], ["My bad! I'll fix it right away.", "내 잘못! 바로 고칠게."]] },
  { id: 231, w: "count on", p: "[kaʊnt ɑːn] 카운트 온", m: "믿다, 의지하다", ex: [["You can count on me.", "나만 믿어."], ["We're counting on you!", "우리 너만 믿고 있어!"]] },
  { id: 232, w: "remind", p: "[rɪˈmaɪnd] 리마인드", m: "상기시키다, 다시 알려주다", ex: [["Remind me to buy milk later.", "나중에 우유 사라고 알려줘."], ["This song reminds me of you.", "이 노래 들으면 네 생각나."]] },
  { id: 233, w: "realize", p: "[ˈriːəlaɪz] 리얼라이즈", m: "깨닫다, 알아차리다", ex: [["I just realized I left my phone at home.", "방금 폰 집에 두고 온 거 깨달았어."], ["I didn't realize it was so late.", "이렇게 늦은 줄 몰랐네."]] },
  { id: 234, w: "notice", p: "[ˈnoʊtɪs] 노티스", m: "알아차리다, 눈치채다", ex: [["Did you notice anything different?", "뭐 달라진 거 못 느꼈어?"], ["I noticed you got a haircut!", "너 머리 자른 거 알아챘어!"]] },
  { id: 235, w: "guess", p: "[ɡes] 게스", m: "추측하다; ~인 것 같아", ex: [["Guess what! I got the job!", "있잖아! 나 취직했어!"], ["I guess you're right.", "네 말이 맞는 것 같아."]] },
  { id: 236, w: "wonder", p: "[ˈwʌndər] 원더", m: "궁금하다", ex: [["I wonder what happened.", "무슨 일이 있었는지 궁금하네."], ["I was wondering if you could help me.", "혹시 도와주실 수 있을까 해서요."]] },
  { id: 237, w: "mention", p: "[ˈmenʃn] 멘션", m: "언급하다, 말을 꺼내다", ex: [["Did he mention me?", "걔가 내 얘기 했어?"], ["Don't mention it!", "별말씀을요! (천만에요)"]] },
  { id: 238, w: "appreciate", p: "[əˈpriːʃieɪt] 어프리시에이트", m: "감사하다, 고마워하다", ex: [["I really appreciate your help.", "도와주셔서 정말 감사해요."], ["I'd appreciate it if you could come early.", "일찍 와주시면 감사하겠습니다."]] },
  { id: 239, w: "apologize", p: "[əˈpɑːlədʒaɪz] 어팔러자이즈", m: "사과하다", ex: [["I want to apologize for being late.", "늦어서 사과드리고 싶어요."], ["You don't need to apologize.", "사과 안 해도 돼."]] },
  { id: 240, w: "forgive", p: "[fərˈɡɪv] 퍼기브", m: "용서하다", ex: [["Please forgive me.", "용서해 줘."], ["I forgave him a long time ago.", "걔는 한참 전에 용서했어."]] },
  { id: 241, w: "blame", p: "[bleɪm] 블레임", m: "탓하다, 비난하다", ex: [["Don't blame yourself.", "자책하지 마."], ["I don't blame you. Anyone would do that.", "네 탓 아니야. 누구라도 그랬을 거야."]] },
  { id: 242, w: "encourage", p: "[ɪnˈkɜːrɪdʒ] 인커리지", m: "격려하다, 응원하다", ex: [["My parents encouraged me to study abroad.", "부모님이 유학 가라고 응원해 주셨어."], ["Thanks for encouraging me.", "격려해 줘서 고마워."]] },
  { id: 243, w: "convince", p: "[kənˈvɪns] 컨빈스", m: "설득하다, 납득시키다", ex: [["I convinced him to join us.", "걔 우리랑 같이 하자고 설득했어."], ["You don't have to convince me. I'm in!", "설득 안 해도 돼. 나 할래!"]] },
  { id: 244, w: "avoid", p: "[əˈvɔɪd] 어보이드", m: "피하다", ex: [["I avoid coffee after 3 p.m.", "오후 3시 이후엔 커피 안 마셔."], ["Are you avoiding me?", "너 나 피하는 거야?"]] },
  { id: 245, w: "handle", p: "[ˈhændl] 핸들", m: "처리하다, 감당하다", ex: [["Don't worry. I can handle it.", "걱정 마. 내가 처리할 수 있어."], ["She handles stress really well.", "걔는 스트레스를 정말 잘 다뤄."]] },
  { id: 246, w: "manage", p: "[ˈmænɪdʒ] 매니지", m: "(간신히) 해내다; 관리하다", ex: [["How do you manage work and study?", "일이랑 공부를 어떻게 다 해?"], ["I managed to finish on time.", "간신히 제시간에 끝냈어."]] },
  { id: 247, w: "focus", p: "[ˈfoʊkəs] 포커스", m: "집중하다", ex: [["I can't focus with this noise.", "이 소음 때문에 집중이 안 돼."], ["Let's focus on the main problem.", "핵심 문제에 집중하자."]] },
  { id: 248, w: "attend", p: "[əˈtend] 어텐드", m: "참석하다", ex: [["Are you attending the wedding?", "그 결혼식 참석해?"], ["I couldn't attend the meeting.", "회의에 참석 못 했어."]] },
  { id: 249, w: "improve", p: "[ɪmˈpruːv] 임프루브", m: "나아지다, 향상시키다", ex: [["Your English is improving fast!", "너 영어 빨리 늘고 있어!"], ["I want to improve my speaking skills.", "말하기 실력을 키우고 싶어."]] },
  { id: 250, w: "practice", p: "[ˈpræktɪs] 프랙티스", m: "연습하다; 연습", ex: [["Practice makes perfect.", "연습이 완벽을 만든다."], ["I practice English every day.", "나 매일 영어 연습해."]] },
  { id: 251, w: "rent", p: "[rent] 렌트", m: "월세, 집세; 빌리다", ex: [["The rent is due tomorrow.", "내일 월세 내는 날이야."], ["We rented a car for the trip.", "여행 가려고 차 빌렸어."]] },
  { id: 252, w: "landlord", p: "[ˈlændlɔːrd] 랜드로드", m: "집주인", ex: [["I'll ask the landlord to fix it.", "집주인한테 고쳐달라고 할게."], ["My landlord raised the rent again.", "집주인이 월세를 또 올렸어."]] },
  { id: 253, w: "utilities", p: "[juːˈtɪlətiz] 유틸리티즈", m: "공과금 (전기·수도·가스)", ex: [["Does the rent include utilities?", "월세에 공과금 포함이에요?"], ["Utilities are expensive in winter.", "겨울엔 공과금이 많이 나와."]] },
  { id: 254, w: "furniture", p: "[ˈfɜːrnɪtʃər] 퍼니처", m: "가구", ex: [["We need new furniture for the living room.", "거실에 새 가구가 필요해."], ["I built this furniture myself!", "이 가구 내가 직접 조립했어!"]] },
  { id: 255, w: "closet", p: "[ˈklɑːzɪt] 클라짓", m: "옷장, 벽장", ex: [["My closet is full of clothes I never wear.", "옷장에 안 입는 옷만 가득해."], ["Hang your coat in the closet.", "코트는 옷장에 걸어."]] },
  { id: 256, w: "drawer", p: "[drɔːr] 드로어", m: "서랍", ex: [["The scissors are in the top drawer.", "가위는 맨 위 서랍에 있어."], ["I keep my socks in this drawer.", "양말은 이 서랍에 넣어둬."]] },
  { id: 257, w: "vacuum", p: "[ˈvækjuːm] 배큠", m: "청소기; 청소기를 돌리다", ex: [["I need to vacuum the living room.", "거실 청소기 돌려야 해."], ["The vacuum is broken again.", "청소기 또 고장 났어."]] },
  { id: 258, w: "chores", p: "[tʃɔːrz] 초어즈", m: "집안일", ex: [["I hate doing chores on weekends.", "주말에 집안일 하는 거 싫어."], ["We split the chores evenly.", "우리는 집안일을 똑같이 나눠서 해."]] },
  { id: 259, w: "neighbor", p: "[ˈneɪbər] 네이버", m: "이웃", ex: [["Our neighbors are really friendly.", "우리 이웃들 진짜 친절해."], ["The neighbor's dog barks all night.", "이웃집 개가 밤새 짖어."]] },
  { id: 260, w: "neighborhood", p: "[ˈneɪbərhʊd] 네이버후드", m: "동네, 인근", ex: [["This is a quiet neighborhood.", "여긴 조용한 동네야."], ["There's a great bakery in my neighborhood.", "우리 동네에 진짜 맛있는 빵집 있어."]] },
  { id: 261, w: "budget", p: "[ˈbʌdʒɪt] 버짓", m: "예산", ex: [["We're on a tight budget.", "우리 예산이 빠듯해."], ["What's your budget for the trip?", "여행 예산이 얼마야?"]] },
  { id: 262, w: "pricey", p: "[ˈpraɪsi] 프라이시", m: "(꽤) 비싼", ex: [["That restaurant is a bit pricey.", "그 식당 좀 비싸."], ["It's pricey, but worth it.", "비싸긴 한데 그만한 가치 있어."]] },
  { id: 263, w: "bargain", p: "[ˈbɑːrɡən] 바겐", m: "싸게 잘 산 물건; 흥정하다", ex: [["This jacket was a real bargain.", "이 재킷 진짜 싸게 잘 샀어."], ["You can bargain at the market.", "시장에서는 흥정할 수 있어."]] },
  { id: 264, w: "wallet", p: "[ˈwɑːlɪt] 왈릿", m: "지갑", ex: [["I left my wallet at home!", "지갑을 집에 두고 왔어!"], ["Someone found my wallet and returned it.", "누가 내 지갑 찾아서 돌려줬어."]] },
  { id: 265, w: "cash", p: "[kæʃ] 캐쉬", m: "현금", ex: [["Do you take cash only?", "현금만 받나요?"], ["I never carry cash these days.", "요즘 현금 안 갖고 다녀."]] },
  { id: 266, w: "change", p: "[tʃeɪndʒ] 체인지", m: "거스름돈, 잔돈", ex: [["Keep the change.", "잔돈은 가지세요."], ["Do you have change for a 50?", "5만 원 잔돈으로 바꿔줄 수 있어?"]] },
  { id: 267, w: "withdraw", p: "[wɪðˈdrɔː] 위드드로", m: "(돈을) 인출하다", ex: [["I need to withdraw some money.", "돈 좀 뽑아야 해."], ["You can withdraw cash at the ATM.", "ATM에서 현금 인출할 수 있어."]] },
  { id: 268, w: "savings", p: "[ˈseɪvɪŋz] 세이빙즈", m: "저축, 모아둔 돈", ex: [["I'm putting half my salary into savings.", "월급의 반은 저축하고 있어."], ["We used our savings for the down payment.", "계약금은 모아둔 돈으로 냈어."]] },
  { id: 269, w: "broke", p: "[broʊk] 브로크", m: "빈털터리인, 돈이 없는", ex: [["I'm broke until payday.", "월급날까지 나 완전 거지야."], ["We were broke back then.", "우리 그때 진짜 돈 없었잖아."]] },
  { id: 270, w: "on sale", p: "[ɑːn seɪl] 온 세일", m: "세일 중인, 할인 중인", ex: [["These shoes are on sale!", "이 신발 세일 중이야!"], ["I only buy clothes when they're on sale.", "난 옷은 세일할 때만 사."]] },
  { id: 271, w: "in advance", p: "[ɪn ədˈvæns] 인 어드밴스", m: "미리, 사전에", ex: [["Please book in advance.", "미리 예약해 주세요."], ["Thanks in advance!", "미리 고마워!"]] },
  { id: 272, w: "last minute", p: "[læst ˈmɪnɪt] 라스트 미닛", m: "막판의, 임박해서", ex: [["He canceled at the last minute.", "걔 막판에 취소했어."], ["I always pack at the last minute.", "난 항상 짐을 닥쳐서 싸."]] },
  { id: 273, w: "run late", p: "[rʌn leɪt] 런 레이트", m: "늦어지다, 지각하다", ex: [["Sorry, I'm running late!", "미안, 나 좀 늦을 것 같아!"], ["The bus is running late again.", "버스가 또 늦네."]] },
  { id: 274, w: "due", p: "[duː] 듀", m: "마감인, 내야 하는", ex: [["The report is due Friday.", "보고서 마감이 금요일이야."], ["When is the assignment due?", "과제 마감이 언제야?"]] },
  { id: 275, w: "promotion", p: "[prəˈmoʊʃn] 프로모션", m: "승진; 판촉", ex: [["Congrats on your promotion!", "승진 축하해!"], ["He got a promotion last month.", "걔 지난달에 승진했어."]] },
  { id: 276, w: "raise", p: "[reɪz] 레이즈", m: "월급 인상; 올리다", ex: [["I'm going to ask for a raise.", "월급 올려달라고 말해볼 거야."], ["She got a raise this year.", "걔 올해 연봉 올랐대."]] },
  { id: 277, w: "quit", p: "[kwɪt] 큇", m: "그만두다", ex: [["I quit my job last month.", "지난달에 일 그만뒀어."], ["Don't quit now. You're so close!", "지금 그만두지 마. 거의 다 왔잖아!"]] },
  { id: 278, w: "retire", p: "[rɪˈtaɪər] 리타이어", m: "은퇴하다", ex: [["My dad retires next year.", "우리 아빠 내년에 은퇴하셔."], ["I want to retire early.", "난 빨리 은퇴하고 싶어."]] },
  { id: 279, w: "resume", p: "[ˈrezəmeɪ] 레저메이", m: "이력서", ex: [["I'm updating my resume.", "이력서 업데이트하는 중이야."], ["Send your resume by email.", "이력서를 이메일로 보내주세요."]] },
  { id: 280, w: "shift", p: "[ʃɪft] 쉬프트", m: "교대 근무", ex: [["I'm working the night shift this week.", "이번 주는 야간 근무야."], ["My shift starts at 9.", "내 근무는 9시에 시작해."]] },
  { id: 281, w: "client", p: "[ˈklaɪənt] 클라이언트", m: "고객, 거래처", ex: [["I have a meeting with a client at 2.", "2시에 거래처 미팅 있어."], ["The client loved our proposal!", "고객이 우리 제안을 엄청 마음에 들어했어!"]] },
  { id: 282, w: "paperwork", p: "[ˈpeɪpərwɜːrk] 페이퍼워크", m: "서류 작업", ex: [["I'm drowning in paperwork.", "서류 작업에 파묻혀 있어."], ["Just fill out this paperwork first.", "먼저 이 서류만 작성해 주세요."]] },
  { id: 283, w: "fever", p: "[ˈfiːvər] 피버", m: "열", ex: [["I think I have a fever.", "나 열 있는 것 같아."], ["Her fever finally went down.", "걔 열이 드디어 내렸어."]] },
  { id: 284, w: "cough", p: "[kɔːf] 코프", m: "기침; 기침하다", ex: [["I can't stop coughing.", "기침이 멈추질 않아."], ["You should see a doctor about that cough.", "그 기침은 병원 가봐야 할 것 같아."]] },
  { id: 285, w: "runny nose", p: "[ˈrʌni noʊz] 러니 노즈", m: "콧물", ex: [["I have a runny nose and a sore throat.", "콧물 나고 목도 아파."], ["My allergies give me a runny nose.", "알레르기 때문에 콧물이 나."]] },
  { id: 286, w: "sneeze", p: "[sniːz] 스니즈", m: "재채기하다", ex: [["I can't stop sneezing!", "재채기가 멈추질 않아!"], ["Cover your mouth when you sneeze.", "재채기할 땐 입을 가려."]] },
  { id: 287, w: "flu", p: "[fluː] 플루", m: "독감", ex: [["I got the flu last week.", "지난주에 독감 걸렸어."], ["Did you get a flu shot?", "독감 주사 맞았어?"]] },
  { id: 288, w: "hangover", p: "[ˈhæŋoʊvər] 행오버", m: "숙취", ex: [["I have a terrible hangover.", "숙취가 너무 심해."], ["What's your hangover cure?", "너만의 숙취 해소법이 뭐야?"]] },
  { id: 289, w: "insomnia", p: "[ɪnˈsɑːmniə] 인삼니아", m: "불면증", ex: [["I've had insomnia lately.", "요즘 불면증이 있어."], ["Coffee at night gives me insomnia.", "밤에 커피 마시면 잠이 안 와."]] },
  { id: 290, w: "stretch", p: "[stretʃ] 스트레치", m: "스트레칭하다, 늘이다", ex: [["Stretch before you exercise.", "운동 전에 스트레칭해."], ["Let me stretch my legs for a bit.", "다리 좀 풀게. (잠깐 걷자)"]] },
  { id: 291, w: "lose weight", p: "[luːz weɪt] 루즈 웨이트", m: "살을 빼다", ex: [["I'm trying to lose weight.", "살 빼려고 노력 중이야."], ["You don't need to lose weight!", "너 살 안 빼도 돼!"]] },
  { id: 292, w: "on a diet", p: "[ɑːn ə ˈdaɪət] 온 어 다이어트", m: "다이어트 중인", ex: [["No cake for me. I'm on a diet.", "난 케이크 빼줘. 다이어트 중이야."], ["I've been on a diet for a month.", "다이어트한 지 한 달 됐어."]] },
  { id: 293, w: "ingredient", p: "[ɪnˈɡriːdiənt] 인그리디언트", m: "재료", ex: [["What ingredients do we need?", "무슨 재료가 필요해?"], ["This dish only needs five ingredients.", "이 요리는 재료가 5개만 있으면 돼."]] },
  { id: 294, w: "recipe", p: "[ˈresəpi] 레서피", m: "레시피, 조리법", ex: [["Can you share the recipe?", "레시피 공유해 줄 수 있어?"], ["I found this recipe online.", "이 레시피 인터넷에서 찾았어."]] },
  { id: 295, w: "homemade", p: "[ˌhoʊmˈmeɪd] 홈메이드", m: "집에서 만든, 수제의", ex: [["Try this homemade cookie!", "이 수제 쿠키 먹어봐!"], ["Nothing beats homemade food.", "집밥만 한 게 없지."]] },
  { id: 296, w: "sour", p: "[ˈsaʊər] 사워", m: "신, 시큼한", ex: [["This lemon is so sour!", "이 레몬 진짜 셔!"], ["The milk smells sour.", "우유에서 쉰내 나."]] },
  { id: 297, w: "bitter", p: "[ˈbɪtər] 비터", m: "쓴", ex: [["This coffee is too bitter for me.", "이 커피 나한텐 너무 써."], ["Dark chocolate is slightly bitter.", "다크초콜릿은 약간 쌉싸름해."]] },
  { id: 298, w: "greasy", p: "[ˈɡriːsi] 그리시", m: "기름진, 느끼한", ex: [["The food was too greasy.", "음식이 너무 느끼했어."], ["I want something greasy today!", "오늘은 기름진 게 당겨!"]] },
  { id: 299, w: "crispy", p: "[ˈkrɪspi] 크리스피", m: "바삭한", ex: [["The chicken is so crispy!", "치킨이 진짜 바삭해!"], ["I like my bacon extra crispy.", "난 베이컨 완전 바삭하게 구운 게 좋아."]] },
  { id: 300, w: "chewy", p: "[ˈtʃuːi] 츄이", m: "쫄깃한, 질긴", ex: [["These rice cakes are nice and chewy.", "이 떡 쫄깃쫄깃하니 맛있다."], ["The steak was a bit chewy.", "스테이크가 좀 질겼어."]] },
  { id: 301, w: "tender", p: "[ˈtendər] 텐더", m: "(고기가) 부드러운, 연한", ex: [["The meat is so tender!", "고기가 진짜 부드러워!"], ["Cook it slowly to make it tender.", "연하게 만들려면 천천히 익혀."]] },
  { id: 302, w: "raw", p: "[rɔː] 로", m: "날것의, 익히지 않은", ex: [["Do you eat raw fish?", "너 회(날생선) 먹어?"], ["The chicken is still raw inside.", "치킨 속이 아직 안 익었어."]] },
  { id: 303, w: "go bad", p: "[ɡoʊ bæd] 고 배드", m: "(음식이) 상하다", ex: [["The milk went bad.", "우유가 상했어."], ["Eat it before it goes bad.", "상하기 전에 먹어."]] },
  { id: 304, w: "heatwave", p: "[ˈhiːtweɪv] 히트웨이브", m: "폭염", ex: [["This heatwave is killing me.", "이 폭염 때문에 죽겠어."], ["The heatwave lasted two weeks.", "폭염이 2주나 갔어."]] },
  { id: 305, w: "shower", p: "[ˈʃaʊər] 샤워", m: "소나기; 샤워", ex: [["We got caught in a shower.", "우리 소나기 만났어."], ["I'll take a quick shower first.", "먼저 빨리 샤워 좀 할게."]] },
  { id: 306, w: "breeze", p: "[briːz] 브리즈", m: "산들바람", ex: [["The breeze feels so nice.", "바람이 너무 좋다."], ["There's a cool breeze tonight.", "오늘 밤은 시원한 바람이 부네."]] },
  { id: 307, w: "eventually", p: "[ɪˈventʃuəli] 이벤츄얼리", m: "결국, 언젠가는", ex: [["You'll get used to it eventually.", "결국엔 익숙해질 거야."], ["Eventually, we found the place.", "결국 우리는 그곳을 찾았어."]] },
  { id: 308, w: "immediately", p: "[ɪˈmiːdiətli] 이미디어틀리", m: "즉시, 바로", ex: [["Call me immediately if anything happens.", "무슨 일 있으면 바로 전화해."], ["I regretted it immediately.", "말하자마자 바로 후회했어."]] },
  { id: 309, w: "recently", p: "[ˈriːsntli] 리슨틀리", m: "최근에", ex: [["I recently started learning English.", "최근에 영어 공부 시작했어."], ["Have you seen any good movies recently?", "최근에 괜찮은 영화 본 거 있어?"]] },
  { id: 310, w: "lately", p: "[ˈleɪtli] 레이틀리", m: "요즘, 최근 들어", ex: [["I've been so busy lately.", "요즘 너무 바빠."], ["How have you been lately?", "요즘 어떻게 지냈어?"]] },
  { id: 311, w: "barely", p: "[ˈberli] 베얼리", m: "간신히, 거의 ~않다", ex: [["I barely slept last night.", "어젯밤에 거의 못 잤어."], ["We barely made the train.", "우리 간신히 기차 탔어."]] },
  { id: 312, w: "suddenly", p: "[ˈsʌdənli] 서든리", m: "갑자기", ex: [["It suddenly started raining.", "갑자기 비가 오기 시작했어."], ["Suddenly, everyone went quiet.", "갑자기 모두가 조용해졌어."]] },
  { id: 313, w: "luckily", p: "[ˈlʌkɪli] 러킬리", m: "다행히, 운 좋게", ex: [["Luckily, no one was hurt.", "다행히 아무도 안 다쳤어."], ["Luckily, I brought an umbrella.", "운 좋게 우산을 챙겨왔지 뭐야."]] },
  { id: 314, w: "honestly", p: "[ˈɑːnɪstli] 어니스틀리", m: "솔직히", ex: [["Honestly, I didn't like the movie.", "솔직히 그 영화 별로였어."], ["Honestly? That's the best pizza ever.", "솔직히? 인생 최고 피자야."]] },
  { id: 315, w: "whole", p: "[hoʊl] 호울", m: "전체의, 통째의", ex: [["I ate the whole pizza by myself.", "피자 한 판을 혼자 다 먹었어."], ["We spent the whole day at the beach.", "우리 하루 종일 해변에 있었어."]] },
  { id: 316, w: "relative", p: "[ˈrelətɪv] 렐러티브", m: "친척", ex: [["All my relatives came for the holiday.", "명절에 친척들이 다 모였어."], ["She's a distant relative of mine.", "걔는 내 먼 친척이야."]] },
  { id: 317, w: "sibling", p: "[ˈsɪblɪŋ] 시블링", m: "형제자매", ex: [["Do you have any siblings?", "형제자매 있어?"], ["I have two siblings — a brother and a sister.", "형제가 둘 있어. 남동생이랑 누나."]] },
  { id: 318, w: "only child", p: "[ˈoʊnli tʃaɪld] 온리 차일드", m: "외동", ex: [["I'm an only child.", "나 외동이야."], ["Being an only child has its perks.", "외동도 좋은 점이 있지."]] },
  { id: 319, w: "in-laws", p: "[ˈɪnlɔːz] 인로즈", m: "처가/시댁 식구", ex: [["We're visiting my in-laws this weekend.", "이번 주말에 처가(시댁)에 가."], ["I get along well with my in-laws.", "난 처가(시댁) 식구들이랑 잘 지내."]] },
  { id: 320, w: "long time no see", p: "[lɔːŋ taɪm noʊ siː] 롱 타임 노 씨", m: "오랜만이야", ex: [["Hey! Long time no see!", "야! 진짜 오랜만이다!"], ["Long time no see. How have you been?", "오랜만이네. 어떻게 지냈어?"]] }
];

// 단어장 테마 분류 (id 목록) — 어떤 테마에도 없는 단어는 단어장에서 "기타"로 표시됨
const THEMES = [
  { name: "💬 회화 필수 표현", ids: [19, 41, 43, 46, 48, 51, 52, 60, 71, 117, 118, 120, 121, 122, 201, 202, 226, 227, 228, 229, 230, 320] },
  { name: "🗣️ 핵심 동사", ids: [1, 33, 42, 53, 54, 55, 56, 57, 72, 148, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 249, 250] },
  { name: "🔗 구동사", ids: [3, 61, 62, 63, 66, 67, 69, 70, 116, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 137, 138, 146, 147, 231] },
  { name: "🎚️ 부사·뉘앙스", ids: [5, 14, 58, 115, 119, 203, 204, 205, 206, 207, 208, 209, 210, 307, 308, 309, 310, 311, 312, 313, 314, 315] },
  { name: "✨ 묘사·평가", ids: [4, 10, 12, 21, 30, 45, 49, 50, 79] },
  { name: "😊 감정·기분", ids: [11, 17, 18, 20, 24, 26, 27, 36, 47, 74, 75, 78, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160] },
  { name: "🙋 성격·사람", ids: [161, 162, 163, 164, 165, 166, 167, 168, 169, 170] },
  { name: "💕 관계·연애", ids: [2, 23, 64, 68, 139, 141, 221, 222, 223, 224, 225] },
  { name: "👨‍👩‍👧 가족", ids: [316, 317, 318, 319] },
  { name: "🍽️ 식당·주문", ids: [28, 34, 38, 44, 96, 97, 98, 145, 191, 192, 193, 194, 195, 196, 197, 198] },
  { name: "😋 음식·맛", ids: [15, 40, 80, 81, 94, 95, 199, 200, 293, 294, 295, 296, 297, 298, 299, 300, 301, 302, 303] },
  { name: "🛒 쇼핑", ids: [35, 85, 86, 134, 175, 176, 177, 178, 179, 180, 270] },
  { name: "💰 돈", ids: [8, 25, 29, 73, 149, 150, 174, 261, 262, 263, 264, 265, 266, 267, 268, 269] },
  { name: "🏠 집·일상", ids: [37, 77, 92, 93, 99, 100, 142, 143, 144, 171, 172, 173, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260] },
  { name: "💼 직장·일", ids: [88, 89, 90, 91, 136, 248, 275, 276, 277, 278, 279, 280, 281, 282] },
  { name: "⏰ 시간·약속", ids: [6, 7, 9, 22, 32, 39, 114, 271, 272, 273, 274] },
  { name: "🤒 건강·운동", ids: [65, 82, 83, 84, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292] },
  { name: "✈️ 여행", ids: [101, 102, 103, 104, 105, 135, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220] },
  { name: "🚇 교통·길찾기", ids: [13, 16, 31, 59, 87, 110, 111, 112, 113, 140] },
  { name: "🌦️ 날씨", ids: [76, 106, 107, 108, 109, 304, 305, 306] }
];
