// 영어회화 빈출 단어 데이터
// w: 단어, p: 발음, m: 뜻, ex: [[영어 예문, 한글 해석], ...]
const WORDS = [
  { id: 1, w: "grab", p: "[ɡræb] 그랩", m: "잡다; (간단히) 먹다, 마시다", ex: [["Let's grab a coffee sometime.", "언제 커피 한잔하자."], ["Can you grab my bag for me?", "내 가방 좀 집어줄래?"]] },
  { id: 2, w: "hang out", p: "[hæŋ aʊt] 행 아웃", m: "놀다, 시간을 보내다", ex: [["Do you want to hang out this weekend?", "이번 주말에 같이 놀래?"], ["I usually hang out with my friends after work.", "나는 보통 퇴근 후에 친구들이랑 놀아."]] },
  { id: 3, w: "figure out", p: "[ˈfɪɡjər aʊt] 피겨 아웃", m: "알아내다, 이해하다", ex: [["I can't figure out how to use this app.", "이 앱을 어떻게 쓰는지 모르겠어."], ["We'll figure it out together.", "우리 같이 방법을 찾아보자."]] },
  { id: 4, w: "awesome", p: "[ˈɔːsəm] 어썸", m: "굉장한, 멋진", ex: [["That movie was awesome!", "그 영화 진짜 멋졌어!"], ["You did an awesome job.", "너 정말 잘했어."]] },
  { id: 5, w: "actually", p: "[ˈæktʃuəli] 액츄얼리", m: "사실은, 실제로", ex: [["Actually, I've never been there.", "사실 나 거기 가본 적 없어."], ["It's actually easier than it looks.", "그거 사실 보기보다 쉬워."]] },
  { id: 6, w: "appointment", p: "[əˈpɔɪntmənt] 어포인트먼트", m: "(병원·업무 등의) 약속, 예약", ex: [["I have a doctor's appointment at 3.", "나 3시에 병원 예약 있어."], ["Can I make an appointment for tomorrow?", "내일로 예약할 수 있을까요?"]] },
  { id: 7, w: "available", p: "[əˈveɪləbl] 어베일러블", m: "시간이 되는; 이용 가능한", ex: [["Are you available this Friday?", "이번 금요일에 시간 돼?"], ["Is this seat available?", "이 자리 비어 있나요?"]] },
  { id: 8, w: "borrow", p: "[ˈbɑːroʊ] 바로우", m: "빌리다", ex: [["Can I borrow your pen?", "펜 좀 빌려도 될까?"], ["I borrowed this book from the library.", "이 책 도서관에서 빌렸어."]] },
  { id: 9, w: "cancel", p: "[ˈkænsl] 캔슬", m: "취소하다", ex: [["I need to cancel my reservation.", "예약을 취소해야 해요."], ["The meeting was canceled.", "회의가 취소됐어."]] },
  { id: 10, w: "comfortable", p: "[ˈkʌmftəbl] 컴프터블", m: "편안한", ex: [["This chair is so comfortable.", "이 의자 정말 편하다."], ["Make yourself comfortable.", "편하게 있어."]] },
  { id: 11, w: "confused", p: "[kənˈfjuːzd] 컨퓨즈드", m: "혼란스러운, 헷갈리는", ex: [["I'm confused. Can you explain again?", "헷갈려요. 다시 설명해 줄래요?"], ["She looked confused by the question.", "그녀는 질문에 헷갈려하는 것 같았어."]] },
  { id: 12, w: "convenient", p: "[kənˈviːniənt] 컨비니언트", m: "편리한", ex: [["Is 2 o'clock convenient for you?", "2시 괜찮으세요?"], ["The subway is really convenient here.", "여기는 지하철이 정말 편리해."]] },
  { id: 13, w: "crowded", p: "[ˈkraʊdɪd] 크라우디드", m: "붐비는, 혼잡한", ex: [["The bus was so crowded this morning.", "오늘 아침 버스 진짜 붐볐어."], ["Let's avoid crowded places.", "붐비는 곳은 피하자."]] },
  { id: 14, w: "definitely", p: "[ˈdefɪnətli] 데피니틀리", m: "확실히, 분명히", ex: [["I'll definitely be there.", "꼭 갈게."], ["This is definitely the best pizza in town.", "이게 확실히 이 동네 최고 피자야."]] },
  { id: 15, w: "delicious", p: "[dɪˈlɪʃəs] 딜리셔스", m: "맛있는", ex: [["This soup is delicious!", "이 수프 맛있다!"], ["Everything was delicious. Thank you.", "전부 맛있었어요. 감사합니다."]] },
  { id: 16, w: "directions", p: "[dəˈrekʃnz] 디렉션즈", m: "길 안내, 방향", ex: [["Could you give me directions to the station?", "역까지 가는 길 좀 알려주실래요?"], ["I'm bad at following directions.", "난 길 찾는 게 서툴러."]] },
  { id: 17, w: "embarrassed", p: "[ɪmˈbærəst] 임배러스트", m: "창피한, 민망한", ex: [["I was so embarrassed when I fell.", "넘어졌을 때 너무 창피했어."], ["Don't be embarrassed. It happens.", "민망해하지 마. 그럴 수 있어."]] },
  { id: 18, w: "exhausted", p: "[ɪɡˈzɔːstɪd] 이그조스티드", m: "몹시 지친, 기진맥진한", ex: [["I'm exhausted after work.", "퇴근하고 나니 완전 지쳤어."], ["You look exhausted. Get some rest.", "너 지쳐 보여. 좀 쉬어."]] },
  { id: 19, w: "favor", p: "[ˈfeɪvər] 페이버", m: "부탁, 호의", ex: [["Can you do me a favor?", "부탁 하나 들어줄래?"], ["I owe you a favor.", "너한테 신세 졌네."]] },
  { id: 20, w: "grateful", p: "[ˈɡreɪtfl] 그레이트풀", m: "감사하는, 고마워하는", ex: [["I'm so grateful for your help.", "도와줘서 정말 고마워."], ["We're grateful to have you here.", "당신이 여기 있어줘서 감사해요."]] },
  { id: 21, w: "hilarious", p: "[hɪˈleriəs] 힐레리어스", m: "아주 웃긴", ex: [["That joke was hilarious!", "그 농담 진짜 웃겼어!"], ["You should watch this video. It's hilarious.", "이 영상 꼭 봐. 완전 웃겨."]] },
  { id: 22, w: "hurry", p: "[ˈhɜːri] 허리", m: "서두르다; 서두름", ex: [["Hurry up, or we'll be late!", "서둘러, 안 그러면 늦어!"], ["There's no hurry. Take your time.", "급할 거 없어. 천천히 해."]] },
  { id: 23, w: "invite", p: "[ɪnˈvaɪt] 인바이트", m: "초대하다", ex: [["I'd like to invite you to my birthday party.", "내 생일 파티에 초대하고 싶어."], ["Thanks for inviting me!", "초대해 줘서 고마워!"]] },
  { id: 24, w: "jealous", p: "[ˈdʒeləs] 젤러스", m: "질투하는, 부러워하는", ex: [["I'm so jealous of your trip!", "네 여행 진짜 부럽다!"], ["He got jealous when he saw us talking.", "걔는 우리가 얘기하는 걸 보고 질투했어."]] },
  { id: 25, w: "lend", p: "[lend] 렌드", m: "빌려주다", ex: [["Can you lend me some money?", "돈 좀 빌려줄 수 있어?"], ["I lent him my umbrella.", "걔한테 우산 빌려줬어."]] },
  { id: 26, w: "mood", p: "[muːd] 무드", m: "기분; 분위기", ex: [["I'm not in the mood to go out.", "나갈 기분이 아니야."], ["She's in a good mood today.", "걔 오늘 기분 좋아."]] },
  { id: 27, w: "nervous", p: "[ˈnɜːrvəs] 너버스", m: "긴장한, 불안한", ex: [["I'm nervous about the interview.", "면접 때문에 긴장돼."], ["Don't be nervous. You'll do great.", "긴장하지 마. 잘할 거야."]] },
  { id: 28, w: "order", p: "[ˈɔːrdər] 오더", m: "주문하다; 주문", ex: [["Are you ready to order?", "주문하시겠어요?"], ["I ordered it online yesterday.", "어제 온라인으로 주문했어."]] },
  { id: 29, w: "owe", p: "[oʊ] 오우", m: "빚지다, 신세 지다", ex: [["How much do I owe you?", "내가 얼마 줘야 하지?"], ["I owe you one!", "신세 한 번 졌네! (고마워!)"]] },
  { id: 30, w: "perfect", p: "[ˈpɜːrfɪkt] 퍼펙트", m: "완벽한; 딱 좋은", ex: [["That time works perfect for me.", "그 시간 나한테 딱 좋아."], ["The weather is perfect today.", "오늘 날씨 완벽하다."]] },
  { id: 31, w: "pick up", p: "[pɪk ʌp] 픽 업", m: "데리러 가다; 찾아오다, 사다", ex: [["I'll pick you up at 7.", "7시에 데리러 갈게."], ["Can you pick up some milk on your way home?", "집에 오는 길에 우유 좀 사다 줄래?"]] },
  { id: 32, w: "plan", p: "[plæn] 플랜", m: "계획; 계획하다", ex: [["Do you have any plans for the weekend?", "주말에 무슨 계획 있어?"], ["We're planning a trip to Jeju.", "우리 제주도 여행 계획 중이야."]] },
  { id: 33, w: "promise", p: "[ˈprɑːmɪs] 프라미스", m: "약속하다; 약속", ex: [["I promise I won't be late.", "늦지 않겠다고 약속할게."], ["You have to keep your promise.", "약속은 지켜야지."]] },
  { id: 34, w: "recommend", p: "[ˌrekəˈmend] 레커멘드", m: "추천하다", ex: [["What do you recommend here?", "여기 뭐가 맛있어요? (추천 메뉴가 뭐예요?)"], ["I highly recommend this book.", "이 책 강력 추천해."]] },
  { id: 35, w: "refund", p: "[ˈriːfʌnd] 리펀드", m: "환불; 환불하다", ex: [["Can I get a refund for this?", "이거 환불 받을 수 있을까요?"], ["They gave me a full refund.", "전액 환불해 줬어."]] },
  { id: 36, w: "regret", p: "[rɪˈɡret] 리그렛", m: "후회하다; 후회", ex: [["I regret not studying English earlier.", "영어 공부를 더 일찍 안 한 게 후회돼."], ["You won't regret it.", "후회하지 않을 거야."]] },
  { id: 37, w: "relax", p: "[rɪˈlæks] 릴랙스", m: "쉬다, 긴장을 풀다", ex: [["I just want to relax at home today.", "오늘은 그냥 집에서 쉬고 싶어."], ["Relax! Everything will be fine.", "긴장 풀어! 다 잘될 거야."]] },
  { id: 38, w: "reservation", p: "[ˌrezərˈveɪʃn] 레저베이션", m: "예약", ex: [["I'd like to make a reservation for two.", "두 명 예약하고 싶은데요."], ["Do you have a reservation?", "예약하셨나요?"]] },
  { id: 39, w: "schedule", p: "[ˈskedʒuːl] 스케줄", m: "일정; 일정을 잡다", ex: [["My schedule is full this week.", "이번 주는 일정이 꽉 찼어."], ["Let's schedule a meeting for Monday.", "월요일로 회의 일정 잡자."]] },
  { id: 40, w: "starving", p: "[ˈstɑːrvɪŋ] 스타빙", m: "몹시 배고픈", ex: [["I'm starving! Let's eat.", "배고파 죽겠어! 밥 먹자."], ["You must be starving after the long trip.", "긴 여행 후라 엄청 배고프겠다."]] },
  { id: 41, w: "stuck", p: "[stʌk] 스턱", m: "갇힌, 막힌, 꼼짝 못 하는", ex: [["I'm stuck in traffic.", "차가 막혀서 꼼짝 못 하고 있어."], ["I'm stuck on this problem.", "이 문제에서 막혔어."]] },
  { id: 42, w: "suggest", p: "[səˈdʒest] 서제스트", m: "제안하다", ex: [["What do you suggest we do?", "우리가 뭘 하면 좋을까? (제안해 줘)"], ["I suggest taking the subway.", "지하철 타는 걸 추천해."]] },
  { id: 43, w: "supposed to", p: "[səˈpoʊzd tu] 서포즈드 투", m: "~하기로 되어 있다", ex: [["You're supposed to be here by 9.", "너 9시까지 오기로 되어 있잖아."], ["What am I supposed to do?", "내가 어떻게 해야 하는 거야?"]] },
  { id: 44, w: "treat", p: "[triːt] 트리트", m: "한턱내다; 대접, 특별한 선물", ex: [["It's my treat today.", "오늘은 내가 살게."], ["Let me treat you to dinner.", "저녁 한턱낼게."]] },
  { id: 45, w: "terrible", p: "[ˈterəbl] 테러블", m: "끔찍한, 형편없는", ex: [["The traffic was terrible today.", "오늘 차 진짜 끔찍하게 막혔어."], ["I feel terrible about what happened.", "그 일은 정말 미안하게 생각해."]] },
  { id: 46, w: "though", p: "[ðoʊ] 도우", m: "~이긴 하지만 (문장 끝에서)", ex: [["It's expensive. It's really good, though.", "비싸긴 해. 그래도 진짜 좋아."], ["Thanks, though.", "그래도 고마워."]] },
  { id: 47, w: "upset", p: "[ʌpˈset] 업셋", m: "속상한, 화가 난", ex: [["Why are you so upset?", "왜 그렇게 속상해해?"], ["She got upset when she heard the news.", "그녀는 그 소식을 듣고 속상해했어."]] },
  { id: 48, w: "used to", p: "[juːst tu] 유스트 투", m: "예전에 ~하곤 했다", ex: [["I used to live in Busan.", "나 예전에 부산 살았어."], ["We used to hang out a lot.", "우리 예전엔 자주 놀았잖아."]] },
  { id: 49, w: "weird", p: "[wɪrd] 위어드", m: "이상한, 기묘한", ex: [["That's so weird.", "그거 진짜 이상하다."], ["I had a weird dream last night.", "어젯밤에 이상한 꿈 꿨어."]] },
  { id: 50, w: "worth", p: "[wɜːrθ] 워스", m: "~할 가치가 있는", ex: [["It's worth a try.", "시도해 볼 만해."], ["The movie is totally worth watching.", "그 영화 진짜 볼 가치 있어."]] },
  { id: 51, w: "excuse", p: "[ɪkˈskjuːs] 익스큐스", m: "변명; 양해를 구하다", ex: [["Excuse me, is anyone sitting here?", "실례합니다, 여기 자리 있나요?"], ["Stop making excuses.", "변명 좀 그만해."]] },
  { id: 52, w: "mind", p: "[maɪnd] 마인드", m: "꺼리다, 신경 쓰다", ex: [["Do you mind if I open the window?", "창문 좀 열어도 될까요?"], ["Never mind. It's not important.", "신경 쓰지 마. 별거 아니야."]] },
  { id: 53, w: "miss", p: "[mɪs] 미스", m: "그리워하다; 놓치다", ex: [["I miss you so much.", "네가 너무 보고 싶어."], ["Hurry, or you'll miss the train!", "서둘러, 안 그러면 기차 놓쳐!"]] },
  { id: 54, w: "bother", p: "[ˈbɑːðər] 바더", m: "귀찮게 하다, 신경 쓰이게 하다", ex: [["Sorry to bother you, but can I ask something?", "귀찮게 해서 미안한데, 뭐 좀 물어봐도 돼?"], ["Don't bother. I'll do it myself.", "신경 쓰지 마. 내가 할게."]] },
  { id: 55, w: "celebrate", p: "[ˈselɪbreɪt] 셀러브레이트", m: "축하하다, 기념하다", ex: [["Let's celebrate your promotion!", "네 승진 축하하자!"], ["How do you celebrate your birthday?", "생일은 어떻게 보내?"]] },
  { id: 56, w: "complain", p: "[kəmˈpleɪn] 컴플레인", m: "불평하다, 항의하다", ex: [["He always complains about work.", "걔는 맨날 일에 대해 불평해."], ["I'd like to complain about the noise.", "소음에 대해 항의하고 싶은데요."]] },
  { id: 57, w: "expect", p: "[ɪkˈspekt] 익스펙트", m: "기대하다, 예상하다", ex: [["I didn't expect to see you here!", "여기서 널 볼 줄 몰랐어!"], ["What did you expect?", "뭘 기대한 거야?"]] },
  { id: 58, w: "literally", p: "[ˈlɪtərəli] 리터럴리", m: "말 그대로, 진짜로", ex: [["I literally just got home.", "나 진짜 방금 집에 왔어."], ["It was literally the best day ever.", "말 그대로 최고의 하루였어."]] },
  { id: 59, w: "on my way", p: "[ɑːn maɪ weɪ] 온 마이 웨이", m: "가는 중인", ex: [["I'm on my way. Be there in 10.", "가는 중이야. 10분 안에 도착해."], ["I'll grab some snacks on my way.", "가는 길에 간식 좀 사 갈게."]] },
  { id: 60, w: "deal", p: "[diːl] 딜", m: "거래, 약속; 좋은 조건", ex: [["It's a deal!", "그렇게 하기로 한 거다! (약속!)"], ["This phone was a really good deal.", "이 폰 진짜 싸게 잘 샀어."]] },
  { id: 61, w: "stop by", p: "[stɑːp baɪ] 스탑 바이", m: "잠깐 들르다", ex: [["Can I stop by your place tonight?", "오늘 밤에 너희 집에 잠깐 들러도 돼?"], ["I stopped by the store on my way home.", "집에 오는 길에 가게에 잠깐 들렀어."]] },
  { id: 62, w: "run into", p: "[rʌn ˈɪntu] 런 인투", m: "우연히 만나다, 마주치다", ex: [["I ran into an old friend yesterday.", "어제 옛 친구를 우연히 만났어."], ["You'll never guess who I ran into!", "내가 누구 마주쳤는지 상상도 못 할걸!"]] },
  { id: 63, w: "look forward to", p: "[lʊk ˈfɔːrwərd tu] 룩 포워드 투", m: "~을 기대하다, 고대하다", ex: [["I'm looking forward to the weekend.", "주말이 너무 기다려져."], ["We look forward to seeing you soon.", "곧 뵙기를 기대할게요."]] },
  { id: 64, w: "get along", p: "[ɡet əˈlɔːŋ] 겟 얼롱", m: "사이좋게 지내다", ex: [["Do you get along with your coworkers?", "직장 동료들이랑 잘 지내?"], ["We get along really well.", "우린 정말 잘 지내."]] },
  { id: 65, w: "work out", p: "[wɜːrk aʊt] 워크 아웃", m: "운동하다; (일이) 잘 풀리다", ex: [["I work out three times a week.", "나 일주일에 세 번 운동해."], ["Don't worry. It'll all work out.", "걱정 마. 다 잘 풀릴 거야."]] },
  { id: 66, w: "show up", p: "[ʃoʊ ʌp] 쇼 업", m: "나타나다, 오다", ex: [["He didn't show up to the meeting.", "걔 회의에 안 나타났어."], ["Just show up by 7, okay?", "7시까지만 와, 알았지?"]] },
  { id: 67, w: "take care of", p: "[teɪk ker əv] 테이크 케어 오브", m: "돌보다; 처리하다", ex: [["I'll take care of the bill.", "계산은 내가 처리할게."], ["She takes care of her little brother.", "걔는 남동생을 돌봐."]] },
  { id: 68, w: "come over", p: "[kʌm ˈoʊvər] 컴 오버", m: "(우리 집에) 오다, 건너오다", ex: [["Why don't you come over for dinner?", "저녁 먹으러 우리 집에 올래?"], ["My friends are coming over tonight.", "오늘 밤에 친구들이 우리 집에 와."]] },
  { id: 69, w: "get over", p: "[ɡet ˈoʊvər] 겟 오버", m: "극복하다, (병·이별에서) 회복하다", ex: [["It took me a while to get over the cold.", "감기 낫는 데 한참 걸렸어."], ["You'll get over it soon.", "곧 괜찮아질 거야."]] },
  { id: 70, w: "end up", p: "[end ʌp] 엔드 업", m: "결국 ~하게 되다", ex: [["We ended up ordering pizza.", "우리 결국 피자 시켰어."], ["I ended up staying home all day.", "결국 하루 종일 집에 있었어."]] },
  { id: 71, w: "make sense", p: "[meɪk sens] 메이크 센스", m: "말이 되다, 이해가 되다", ex: [["That makes sense.", "그거 말이 되네. (이해돼.)"], ["This sentence doesn't make sense.", "이 문장은 말이 안 돼."]] },
  { id: 72, w: "deserve", p: "[dɪˈzɜːrv] 디저브", m: "~을 받을 자격이 있다", ex: [["You deserve a break.", "넌 쉴 자격이 있어."], ["She deserves the award.", "그녀는 상 받을 만해."]] },
  { id: 73, w: "afford", p: "[əˈfɔːrd] 어포드", m: "~할 (금전적) 여유가 있다", ex: [["I can't afford a new car right now.", "지금은 새 차 살 여유가 없어."], ["Can we afford to eat out tonight?", "오늘 외식할 여유 될까?"]] },
  { id: 74, w: "annoying", p: "[əˈnɔɪɪŋ] 어노잉", m: "짜증나는, 성가신", ex: [["The noise is so annoying.", "그 소음 진짜 짜증나."], ["He can be annoying sometimes.", "걔 가끔 짜증나게 할 때 있어."]] },
  { id: 75, w: "awkward", p: "[ˈɔːkwərd] 어쿼드", m: "어색한, 곤란한", ex: [["There was an awkward silence.", "어색한 침묵이 흘렀어."], ["It was so awkward seeing my ex.", "전 애인을 마주쳐서 너무 어색했어."]] },
  { id: 76, w: "chilly", p: "[ˈtʃɪli] 칠리", m: "쌀쌀한", ex: [["It's a bit chilly today.", "오늘 좀 쌀쌀하네."], ["Take a jacket. It gets chilly at night.", "재킷 챙겨. 밤엔 쌀쌀해져."]] },
  { id: 77, w: "cozy", p: "[ˈkoʊzi] 코지", m: "아늑한, 포근한", ex: [["This cafe is so cozy.", "이 카페 진짜 아늑하다."], ["I love staying cozy at home on rainy days.", "비 오는 날엔 집에서 포근하게 있는 게 좋아."]] },
  { id: 78, w: "disappointed", p: "[ˌdɪsəˈpɔɪntɪd] 디서포인티드", m: "실망한", ex: [["I was disappointed with the movie.", "그 영화 실망스러웠어."], ["Don't be disappointed. There's always next time.", "실망하지 마. 다음 기회가 있잖아."]] },
  { id: 79, w: "fancy", p: "[ˈfænsi] 팬시", m: "고급스러운, 화려한", ex: [["We went to a fancy restaurant.", "우리 고급 레스토랑에 갔어."], ["You look fancy today! What's the occasion?", "오늘 쫙 빼입었네! 무슨 날이야?"]] },
  { id: 80, w: "spicy", p: "[ˈspaɪsi] 스파이시", m: "매운", ex: [["Is this dish spicy?", "이 음식 매워요?"], ["I can't handle spicy food.", "난 매운 거 잘 못 먹어."]] },
  { id: 81, w: "thirsty", p: "[ˈθɜːrsti] 써스티", m: "목마른", ex: [["I'm so thirsty. Let's get something to drink.", "목말라 죽겠어. 뭐 좀 마시러 가자."], ["This salty food makes me thirsty.", "이 짠 음식 때문에 목말라."]] },
  { id: 82, w: "dizzy", p: "[ˈdɪzi] 디지", m: "어지러운", ex: [["I feel dizzy when I stand up.", "일어나면 어지러워."], ["The ride made me dizzy.", "놀이기구 타고 어지러웠어."]] },
  { id: 83, w: "sore", p: "[sɔːr] 쏘어", m: "아픈, 쑤시는 (근육·목 등)", ex: [["I have a sore throat.", "목이 아파요. (인후통)"], ["My legs are sore from the workout.", "운동했더니 다리가 쑤셔."]] },
  { id: 84, w: "allergic", p: "[əˈlɜːrdʒɪk] 얼러직", m: "알레르기가 있는", ex: [["I'm allergic to peanuts.", "저 땅콩 알레르기 있어요."], ["Are you allergic to anything?", "알레르기 있는 거 있어요?"]] },
  { id: 85, w: "receipt", p: "[rɪˈsiːt] 리시트", m: "영수증", ex: [["Can I get a receipt, please?", "영수증 주시겠어요?"], ["Keep the receipt in case you need a refund.", "환불할 수도 있으니 영수증 챙겨놔."]] },
  { id: 86, w: "line", p: "[laɪn] 라인", m: "줄; 줄을 서다", ex: [["Is this the line for tickets?", "이게 티켓 줄인가요?"], ["We waited in line for an hour.", "우리 한 시간 동안 줄 섰어."]] },
  { id: 87, w: "traffic", p: "[ˈtræfɪk] 트래픽", m: "교통(량), 차량 정체", ex: [["There's heavy traffic this morning.", "오늘 아침 차가 엄청 막혀."], ["Sorry I'm late. The traffic was terrible.", "늦어서 미안. 차가 너무 막혔어."]] },
  { id: 88, w: "deadline", p: "[ˈdedlaɪn] 데드라인", m: "마감 기한", ex: [["The deadline is this Friday.", "마감이 이번 금요일이야."], ["I'm racing to meet the deadline.", "마감 맞추려고 달리는 중이야."]] },
  { id: 89, w: "day off", p: "[deɪ ɔːf] 데이 오프", m: "쉬는 날, 휴무", ex: [["Tomorrow is my day off.", "내일 나 쉬는 날이야."], ["I need a day off so badly.", "하루 쉬는 게 절실해."]] },
  { id: 90, w: "overtime", p: "[ˈoʊvərtaɪm] 오버타임", m: "야근, 초과 근무", ex: [["I worked overtime again last night.", "어젯밤에 또 야근했어."], ["Do you get paid for overtime?", "야근 수당 받아?"]] },
  { id: 91, w: "coworker", p: "[ˈkoʊwɜːrkər] 코워커", m: "직장 동료", ex: [["My coworkers are really nice.", "내 직장 동료들 진짜 좋아."], ["I'm having lunch with a coworker.", "동료랑 점심 먹는 중이야."]] },
  { id: 92, w: "errand", p: "[ˈerənd] 에런드", m: "심부름, 볼일", ex: [["I have to run some errands today.", "오늘 볼일 좀 봐야 해."], ["Can you do an errand for me?", "심부름 하나만 해줄래?"]] },
  { id: 93, w: "laundry", p: "[ˈlɔːndri] 런드리", m: "빨래, 세탁물", ex: [["I need to do the laundry today.", "오늘 빨래해야 해."], ["The laundry is piling up.", "빨랫감이 쌓여가고 있어."]] },
  { id: 94, w: "leftover", p: "[ˈleftoʊvər] 레프트오버", m: "남은 음식", ex: [["We had leftovers for lunch.", "점심으로 남은 음식 먹었어."], ["Can I take the leftovers home?", "남은 거 싸 갈 수 있을까요?"]] },
  { id: 95, w: "craving", p: "[ˈkreɪvɪŋ] 크레이빙", m: "(특정 음식이) 당김, 갈망", ex: [["I have a craving for chicken.", "치킨이 당겨."], ["I'm craving something sweet.", "단 게 먹고 싶어."]] },
  { id: 96, w: "split", p: "[splɪt] 스플릿", m: "나누다 (비용을 분담하다)", ex: [["Let's split the bill.", "계산은 나눠서 내자. (더치페이하자)"], ["We split the pizza in half.", "우리 피자 반씩 나눠 먹었어."]] },
  { id: 97, w: "to go", p: "[tu ɡoʊ] 투 고", m: "포장해서, 테이크아웃으로", ex: [["Can I get this to go?", "이거 포장해 주시겠어요?"], ["Two coffees to go, please.", "커피 두 잔 포장이요."]] },
  { id: 98, w: "refill", p: "[ˈriːfɪl] 리필", m: "리필; 다시 채우다", ex: [["Can I get a refill, please?", "리필 가능할까요?"], ["Refills are free here.", "여긴 리필이 공짜야."]] },
  { id: 99, w: "charger", p: "[ˈtʃɑːrdʒər] 차저", m: "충전기", ex: [["Did you bring your charger?", "충전기 가져왔어?"], ["Can I borrow your phone charger?", "폰 충전기 좀 빌릴 수 있을까?"]] },
  { id: 100, w: "outlet", p: "[ˈaʊtlet] 아웃렛", m: "콘센트", ex: [["Is there an outlet near here?", "이 근처에 콘센트 있나요?"], ["All the outlets in this cafe are taken.", "이 카페 콘센트 자리 다 찼어."]] },
  { id: 101, w: "luggage", p: "[ˈlʌɡɪdʒ] 러기지", m: "짐, 수하물", ex: [["How much luggage do you have?", "짐이 얼마나 돼?"], ["My luggage didn't arrive!", "제 짐이 안 왔어요!"]] },
  { id: 102, w: "round trip", p: "[raʊnd trɪp] 라운드 트립", m: "왕복 (여행·표)", ex: [["A round trip ticket to Busan, please.", "부산 왕복표 한 장 주세요."], ["How much is a round trip?", "왕복은 얼마예요?"]] },
  { id: 103, w: "book", p: "[bʊk] 북", m: "예약하다", ex: [["I booked a hotel for two nights.", "호텔 2박 예약했어."], ["Should we book in advance?", "미리 예약해야 할까?"]] },
  { id: 104, w: "check in", p: "[tʃek ɪn] 체크 인", m: "체크인하다, 탑승 수속하다", ex: [["What time can we check in?", "몇 시에 체크인할 수 있나요?"], ["I checked in online already.", "온라인으로 이미 체크인했어."]] },
  { id: 105, w: "souvenir", p: "[ˌsuːvəˈnɪr] 수버니어", m: "기념품", ex: [["I bought some souvenirs for my family.", "가족들 주려고 기념품 좀 샀어."], ["This is a souvenir from my trip to Japan.", "이거 일본 여행 기념품이야."]] },
  { id: 106, w: "forecast", p: "[ˈfɔːrkæst] 포어캐스트", m: "(날씨) 예보", ex: [["What's the forecast for tomorrow?", "내일 일기예보 어때?"], ["The forecast says it'll rain.", "예보에서 비 온대."]] },
  { id: 107, w: "humid", p: "[ˈhjuːmɪd] 휴미드", m: "습한", ex: [["It's so humid today.", "오늘 진짜 습하다."], ["Korean summers are hot and humid.", "한국 여름은 덥고 습해."]] },
  { id: 108, w: "pour", p: "[pɔːr] 포어", m: "(비가) 퍼붓다; 따르다", ex: [["It's pouring outside!", "밖에 비 퍼붓고 있어!"], ["Could you pour me some water?", "물 좀 따라 줄래?"]] },
  { id: 109, w: "freezing", p: "[ˈfriːzɪŋ] 프리징", m: "꽁꽁 얼게 추운", ex: [["It's freezing out here!", "여기 밖 얼어 죽겠어!"], ["My hands are freezing.", "손이 꽁꽁 얼었어."]] },
  { id: 110, w: "get off", p: "[ɡet ɔːf] 겟 오프", m: "(버스·지하철에서) 내리다; 퇴근하다", ex: [["We get off at the next stop.", "우리 다음 정거장에서 내려."], ["What time do you get off work?", "몇 시에 퇴근해?"]] },
  { id: 111, w: "transfer", p: "[ˈtrænsfɜːr] 트랜스퍼", m: "환승하다; 옮기다", ex: [["Transfer to Line 2 at City Hall.", "시청역에서 2호선으로 환승하세요."], ["Do I need to transfer?", "환승해야 하나요?"]] },
  { id: 112, w: "fare", p: "[fer] 페어", m: "(교통) 요금", ex: [["How much is the bus fare?", "버스 요금이 얼마예요?"], ["Taxi fares went up again.", "택시 요금 또 올랐어."]] },
  { id: 113, w: "shortcut", p: "[ˈʃɔːrtkʌt] 쇼트컷", m: "지름길", ex: [["I know a shortcut to the station.", "역까지 가는 지름길 알아."], ["Let's take a shortcut through the park.", "공원 가로질러서 지름길로 가자."]] },
  { id: 114, w: "on time", p: "[ɑːn taɪm] 온 타임", m: "제시간에, 정각에", ex: [["The train arrived on time.", "기차가 제시간에 도착했어."], ["Please be on time tomorrow.", "내일은 제시간에 와 줘."]] },
  { id: 115, w: "in a row", p: "[ɪn ə roʊ] 인 어 로우", m: "연속으로", ex: [["It rained three days in a row.", "3일 연속으로 비가 왔어."], ["I've studied English 10 days in a row!", "나 10일 연속 영어 공부했어!"]] },
  { id: 116, w: "run out of", p: "[rʌn aʊt əv] 런 아웃 오브", m: "~이 다 떨어지다", ex: [["We ran out of milk.", "우유가 다 떨어졌어."], ["My phone is running out of battery.", "폰 배터리가 다 돼 가."]] },
  { id: 117, w: "in the middle of", p: "[ɪn ðə ˈmɪdl əv] 인 더 미들 오브", m: "~하는 중인, 한가운데인", ex: [["I'm in the middle of something. Can I call you back?", "지금 뭐 하는 중이라, 다시 전화해도 될까?"], ["He left in the middle of the movie.", "걔 영화 보다가 중간에 나갔어."]] },
  { id: 118, w: "by the way", p: "[baɪ ðə weɪ] 바이 더 웨이", m: "그건 그렇고, 참", ex: [["By the way, did you hear the news?", "그건 그렇고, 그 소식 들었어?"], ["By the way, I love your shoes.", "참, 네 신발 진짜 예쁘다."]] },
  { id: 119, w: "kind of", p: "[kaɪnd əv] 카인드 오브", m: "약간, 어느 정도 (= 좀)", ex: [["I'm kind of tired today.", "나 오늘 좀 피곤해."], ["It's kind of complicated.", "그게 좀 복잡해."]] },
  { id: 120, w: "no wonder", p: "[noʊ ˈwʌndər] 노 원더", m: "어쩐지, 그럴 만하다", ex: [["No wonder you're tired. You barely slept!", "어쩐지 피곤하더라. 너 거의 못 잤잖아!"], ["No wonder this place is always crowded.", "어쩐지 여기 항상 붐비더라."]] }
];
